/*
  ==============================================================================

  This is an automatically generated GUI class created by the Projucer!

  Be careful when adding custom code to these files, as only the code within
  the "//[xyz]" and "//[/xyz]" sections will be retained when the file is loaded
  and re-saved.

  Created with Projucer version: 5.3.2

  ------------------------------------------------------------------------------

  The Projucer is part of the JUCE library.
  Copyright (c) 2017 - ROLI Ltd.

  ==============================================================================
*/

//[Headers] You can add your own extra header files here...
#include "Tag.h"
#include "AudioThumbnailTutorial_04.h"
#include <vector>
using namespace std;
//[/Headers]

#include "frontend.h"


//[MiscUserDefs] You can add your own user definitions and misc code here...

vector<vector<Tag*>> tagSetFromGivenSlice;
vector<Tag*> tagSet;
vector<double> waveformMarkers;
//[/MiscUserDefs]

//==============================================================================
FrontEnd::FrontEnd ()
{
    //[Constructor_pre] You can add your own custom stuff here..
    waveformEditor = new MainContentComponent();
    waveformEditor->setBounds(8, 216, 584, 176);
    addAndMakeVisible(waveformEditor);
    //[/Constructor_pre]

    addTagButton.reset (new ImageButton ("addTagButton"));
    addAndMakeVisible (addTagButton.get());
    addTagButton->setTooltip (TRANS("Add a new slice tag"));
    addTagButton->setButtonText (TRANS("Add Label"));
    addTagButton->addListener (this);

    addTagButton->setImages (false, true, true,
                             ImageCache::getFromMemory (plus_button_up_png, plus_button_up_pngSize), 1.000f, Colour (0x00000000),
                             ImageCache::getFromMemory (plus_button_up_png, plus_button_up_pngSize), 1.000f, Colour (0x00000000),
                             ImageCache::getFromMemory (plus_button_down_png, plus_button_down_pngSize), 1.000f, Colour (0x00000000));
    addTagButton->setBounds (560, 144, 24, 24);

    label.reset (new Label ("autoGenTitleLabel",
                            TRANS("Autogenerated Slice Title:")));
    addAndMakeVisible (label.get());
    label->setTooltip (TRANS("Name automatically generated by current slice\'s tags"));
    label->setFont (Font ("Avenir Next", 17.30f, Font::plain).withTypefaceStyle ("Regular"));
    label->setJustificationType (Justification::centredLeft);
    label->setEditable (false, false, false);
    label->setColour (Label::textColourId, Colour (0xff878787));
    label->setColour (TextEditor::textColourId, Colours::black);
    label->setColour (TextEditor::backgroundColourId, Colour (0x00000000));

    label->setBounds (8, 96, 176, 35);

    saveSectionLabel.reset (new Label ("saveSectionLabel",
                                       TRANS("Save")));
    addAndMakeVisible (saveSectionLabel.get());
    saveSectionLabel->setFont (Font (15.00f, Font::plain).withTypefaceStyle ("Regular"));
    saveSectionLabel->setJustificationType (Justification::centredLeft);
    saveSectionLabel->setEditable (false, false, false);
    saveSectionLabel->setColour (Label::textColourId, Colour (0xff878787));
    saveSectionLabel->setColour (TextEditor::textColourId, Colours::black);
    saveSectionLabel->setColour (TextEditor::backgroundColourId, Colour (0x00000000));

    saveSectionLabel->setBounds (8, 16, 150, 22);

    waveformEditorLabel.reset (new Label ("waveformEditorLabel",
                                          TRANS("Waveform Editor")));
    addAndMakeVisible (waveformEditorLabel.get());
    waveformEditorLabel->setTooltip (TRANS("Import and edit sample markers here"));
    waveformEditorLabel->setFont (Font ("Avenir Next", 17.30f, Font::plain).withTypefaceStyle ("Regular"));
    waveformEditorLabel->setJustificationType (Justification::centredLeft);
    waveformEditorLabel->setEditable (false, false, false);
    waveformEditorLabel->setColour (Label::textColourId, Colour (0xff878787));
    waveformEditorLabel->setColour (TextEditor::textColourId, Colours::black);
    waveformEditorLabel->setColour (TextEditor::backgroundColourId, Colour (0x00000000));

    waveformEditorLabel->setBounds (8, 192, 176, 21);

    addMarkerButton.reset (new ImageButton ("addMarkerButton"));
    addAndMakeVisible (addMarkerButton.get());
    addMarkerButton->setTooltip (TRANS("Add a new marker to sample"));
    addMarkerButton->setButtonText (TRANS("Add Label"));
    addMarkerButton->addListener (this);

    addMarkerButton->setImages (false, true, true,
                                ImageCache::getFromMemory (plus_button_up_png, plus_button_up_pngSize), 1.000f, Colour (0x00000000),
                                ImageCache::getFromMemory (plus_button_up_png, plus_button_up_pngSize), 1.000f, Colour (0x00000000),
                                ImageCache::getFromMemory (plus_button_down_png, plus_button_down_pngSize), 1.000f, Colour (0x00000000));
    addMarkerButton->setBounds (560, 361, 24, 24);

    saveAllSlicesButton.reset (new TextButton ("saveAllSlicesButton"));
    addAndMakeVisible (saveAllSlicesButton.get());
    saveAllSlicesButton->setTooltip (TRANS("Saves all slices within waveform editor based on tags describing each slice of the sample"));
    saveAllSlicesButton->setButtonText (TRANS("Save All Slices"));
    saveAllSlicesButton->addListener (this);
    saveAllSlicesButton->setColour (TextButton::buttonColourId, Colour (0xffb4a7d6));

    saveAllSlicesButton->setBounds (16, 48, 104, 24);

    manualSaveButton.reset (new TextButton ("manualSaveButton"));
    addAndMakeVisible (manualSaveButton.get());
    manualSaveButton->setTooltip (TRANS("Manually save currently selected slice of sample with custom name"));
    manualSaveButton->setButtonText (TRANS("Manually Save Current Slice"));
    manualSaveButton->addListener (this);
    manualSaveButton->setColour (TextButton::buttonColourId, Colour (0xffb4a7d6));

    manualSaveButton->setBounds (128, 48, 184, 24);

    currentSliceAutogenTitle.reset (new Label ("currentSliceAutogenTitle",
                                               TRANS("[No slice currently selected]")));
    addAndMakeVisible (currentSliceAutogenTitle.get());
    currentSliceAutogenTitle->setFont (Font ("Avenir Next", 17.30f, Font::plain).withTypefaceStyle ("Regular"));
    currentSliceAutogenTitle->setJustificationType (Justification::centredLeft);
    currentSliceAutogenTitle->setEditable (false, false, false);
    currentSliceAutogenTitle->setColour (Label::textColourId, Colour (0xff878787));
    currentSliceAutogenTitle->setColour (TextEditor::textColourId, Colours::black);
    currentSliceAutogenTitle->setColour (TextEditor::backgroundColourId, Colour (0x00000000));

    currentSliceAutogenTitle->setBounds (168, 104, 416, 19);

    tagRenameEditor.reset (new TextEditor ("tagRenameEditor"));
    addAndMakeVisible (tagRenameEditor.get());
    tagRenameEditor->setMultiLine (false);
    tagRenameEditor->setReturnKeyStartsNewLine (false);
    tagRenameEditor->setReadOnly (false);
    tagRenameEditor->setScrollbarsShown (false);
    tagRenameEditor->setCaretVisible (true);
    tagRenameEditor->setPopupMenuEnabled (true);
    tagRenameEditor->setColour (TextEditor::textColourId, Colour (0xffcdcdcd));
    tagRenameEditor->setColour (TextEditor::backgroundColourId, Colours::white);
    tagRenameEditor->setColour (TextEditor::highlightColourId, Colour (0xffb4a7d6));
    tagRenameEditor->setColour (TextEditor::outlineColourId, Colour (0xffcdcdcd));
    tagRenameEditor->setColour (TextEditor::shadowColourId, Colours::white);
    tagRenameEditor->setColour (CaretComponent::caretColourId, Colour (0xffb4a7d6));
    tagRenameEditor->setText (TRANS("rename selected tag"));

    tagRenameEditor->setBounds (16, 160, 536, 16);


    //[UserPreSize]
    //[/UserPreSize]

    setSize (600, 400);


    //[Constructor] You can add your own custom stuff here..
    //[/Constructor]
}

FrontEnd::~FrontEnd()
{
    //[Destructor_pre]. You can add your own custom destruction code here..
    tagSet.clear();
    waveformEditor = nullptr;
    //[/Destructor_pre]

    addTagButton = nullptr;
    label = nullptr;
    saveSectionLabel = nullptr;
    waveformEditorLabel = nullptr;
    addMarkerButton = nullptr;
    saveAllSlicesButton = nullptr;
    manualSaveButton = nullptr;
    currentSliceAutogenTitle = nullptr;
    tagRenameEditor = nullptr;


    //[Destructor]. You can add your own custom destruction code here..
    //[/Destructor]
}

//==============================================================================
void FrontEnd::paint (Graphics& g)
{
    //[UserPrePaint] Add your own custom painting code here..
    //[/UserPrePaint]

    g.fillAll (Colour (0xffb4a7d6));

    {
        float x = 8.0f, y = 98.0f, width = 584.0f, height = 78.0f;
        Colour fillColour = Colour (0xffcdcdcd);
        //[UserPaintCustomArguments] Customize the painting arguments here..
        //[/UserPaintCustomArguments]
        g.setColour (fillColour);
        g.fillRoundedRectangle (x, y, width, height, 10.000f);
    }

    {
        float x = 8.0f, y = 128.0f, width = 584.0f, height = 48.0f;
        Colour fillColour = Colours::white;
        //[UserPaintCustomArguments] Customize the painting arguments here..
        //[/UserPaintCustomArguments]
        g.setColour (fillColour);
        g.fillRoundedRectangle (x, y, width, height, 10.000f);
    }

    {
        int x = 8, y = 128, width = 584, height = 22;
        Colour fillColour = Colours::white;
        //[UserPaintCustomArguments] Customize the painting arguments here..
        //[/UserPaintCustomArguments]
        g.setColour (fillColour);
        g.fillRect (x, y, width, height);
    }

    {
        float x = 8.0f, y = 186.0f, width = 584.0f, height = 184.0f;
        Colour fillColour = Colour (0xffcdcdcd);
        //[UserPaintCustomArguments] Customize the painting arguments here..
        //[/UserPaintCustomArguments]
        g.setColour (fillColour);
        g.fillRoundedRectangle (x, y, width, height, 10.000f);
    }

    {
        float x = 8.0f, y = 290.0f, width = 584.0f, height = 102.0f;
        Colour fillColour = Colours::white;
        //[UserPaintCustomArguments] Customize the painting arguments here..
        //[/UserPaintCustomArguments]
        g.setColour (fillColour);
        g.fillRoundedRectangle (x, y, width, height, 10.000f);
    }

    {
        int x = 8, y = 216, width = 584, height = 80;
        Colour fillColour = Colours::white;
        //[UserPaintCustomArguments] Customize the painting arguments here..
        //[/UserPaintCustomArguments]
        g.setColour (fillColour);
        g.fillRect (x, y, width, height);
    }

    {
        float x = 8.0f, y = 10.0f, width = 584.0f, height = 78.0f;
        Colour fillColour = Colour (0xffcdcdcd);
        //[UserPaintCustomArguments] Customize the painting arguments here..
        //[/UserPaintCustomArguments]
        g.setColour (fillColour);
        g.fillRoundedRectangle (x, y, width, height, 10.000f);
    }

    {
        float x = 8.0f, y = 40.0f, width = 584.0f, height = 48.0f;
        Colour fillColour = Colours::white;
        //[UserPaintCustomArguments] Customize the painting arguments here..
        //[/UserPaintCustomArguments]
        g.setColour (fillColour);
        g.fillRoundedRectangle (x, y, width, height, 10.000f);
    }

    {
        int x = 8, y = 40, width = 584, height = 24;
        Colour fillColour = Colours::white;
        //[UserPaintCustomArguments] Customize the painting arguments here..
        //[/UserPaintCustomArguments]
        g.setColour (fillColour);
        g.fillRect (x, y, width, height);
    }

    //[UserPaint] Add your own custom painting code here..
    //[/UserPaint]
}

void FrontEnd::resized()
{
    //[UserPreResize] Add your own custom resize code here..
    //[/UserPreResize]

    //[UserResized] Add your own custom resize handling here..
    //[/UserResized]
}

void FrontEnd::buttonClicked (Button* buttonThatWasClicked)
{
    //[UserbuttonClicked_Pre]
    //[/UserbuttonClicked_Pre]

    if (buttonThatWasClicked == addTagButton.get())
    {
        //[UserButtonCode_addTagButton] -- add your button handler code here..
        tagRenameEditor->setText("");
        if(tagSet.size() < 8){
            Tag* newTag = new Tag();
            tagSet.push_back(newTag);
            reorganizeTags();
        }

        //[/UserButtonCode_addTagButton]
    }
    else if (buttonThatWasClicked == addMarkerButton.get())
    {
        //[UserButtonCode_addMarkerButton] -- add your button handler code here..
        waveformEditor->addMarkerAtCurrentPosition();
        tagSetFromGivenSlice.push_back(*new vector<Tag*>);
        waveformEditor->repaint();
        //[/UserButtonCode_addMarkerButton]
    }
    else if (buttonThatWasClicked == saveAllSlicesButton.get())
    {
        //[UserButtonCode_saveAllSlicesButton] -- add your button handler code here..
        //[/UserButtonCode_saveAllSlicesButton]
    }
    else if (buttonThatWasClicked == manualSaveButton.get())
    {
        //[UserButtonCode_manualSaveButton] -- add your button handler code here..
        //[/UserButtonCode_manualSaveButton]
    }

    //[UserbuttonClicked_Post]
    //[/UserbuttonClicked_Post]
}

void FrontEnd::mouseDown (const MouseEvent& e)
{
    //[UserCode_mouseDown] -- Add your code here...
    //[/UserCode_mouseDown]
}

void FrontEnd::mouseDrag (const MouseEvent& e)
{
    //[UserCode_mouseDrag] -- Add your code here...
    //[/UserCode_mouseDrag]
}

void FrontEnd::mouseDoubleClick (const MouseEvent& e)
{
    //[UserCode_mouseDoubleClick] -- Add your code here...
    //[/UserCode_mouseDoubleClick]
}



//[MiscUserCode] You can add your own definitions of your custom methods or any other code here...

void FrontEnd:: deleteTag(Tag* t){

    vector<Tag*>::iterator tagIterator = tagSet.begin();

    for(int i = 0; i < tagSet.size(); i++){
        if(tagSet[i] == tagToDelete)
        {
            tagSet.erase(tagIterator);
            reorganizeTags();
            break;
        }
        tagIterator++;
    }
}

void FrontEnd:: renameTag(Tag* t){
    String newText = tagRenameEditor->getText();
    if(newText.isNotEmpty()){
        t->setText(tagRenameEditor->getText());
        t->repaint();
        tagRenameEditor->setText("");
    }
}

void FrontEnd:: resizeTags(){

    //if tagSet isn't empty, set each tag's width to be the total area divided by the number
    //of tags available
    if(!tagSet.empty())
        fittedTagWidth = 530/tagSet.size();

    //if no tags are available, set the tag width to 0
    else
        fittedTagWidth = 0;

    //iterate over the tags and set their widths and x posiitions to reflect the number of tags there are
    for(int i = 0; i < tagSet.size(); i++){
        tagSet[i]->setBounds(16 + i * (fittedTagWidth + 2), 136, fittedTagWidth, 24);
        addAndMakeVisible(tagSet[i]);
    }
}

void FrontEnd:: updateAutogenLabel(){
    //reinitialize slice title as empty string so that it can be appended to based on order of tags
    String titleFromTags= "";

    //set autogen label to read "[No tags available]" when none have been created
    if(tagSet.size() == 0){
        titleFromTags = "[No tags available]";
    }
    else
    {
        //iterate over all current tags
        for(int i = 0; i < tagSet.size(); i++){

            //append each tag's (custom) text to autogenerated filename
            if(tagSet[i]->getText() != "click to rename"){

                //if the tag being read from is not the final tag, add a space between words
                if(i != tagSet.size() - 1)
                {
                    titleFromTags.append((tagSet[i]->getText()), 25);
                    titleFromTags.append(" ", 1);
                }

                //if this is the final tag, do not add a space after its name is appended
                else
                {
                    titleFromTags.append(tagSet[i]->getText(), 25);
                }
            }
        }
        titleFromTags.append(".wav", 4);
    }

    //set the label's text value to the generated string from the tag names
    currentSliceAutogenTitle->setText(titleFromTags, juce::dontSendNotification);
}

void FrontEnd:: reorganizeTags(){
    
    //handle any tag deletion that needs to occur from double-clicks on a tag
    if(tagToDelete != nullptr) deleteTag(tagToDelete);

    //handle any tag renaming that needs to occur from single-clicks on a tag
    if(tagToRename != nullptr) renameTag(tagToRename);

    //resize whatever number of tags there currently are to fit within their area
    resizeTags();

    //update label based on tags' current order & names
    updateAutogenLabel();
}

//[/MiscUserCode]


//==============================================================================
#if 0
/*  -- Projucer information section --

    This is where the Projucer stores the metadata that describe this GUI layout, so
    make changes in here at your peril!

BEGIN_JUCER_METADATA

<JUCER_COMPONENT documentType="Component" className="FrontEnd" componentName=""
                 parentClasses="public Component" constructorParams="" variableInitialisers=""
                 snapPixels="8" snapActive="1" snapShown="1" overlayOpacity="0.330"
                 fixedSize="1" initialWidth="600" initialHeight="400">
  <METHODS>
    <METHOD name="mouseDoubleClick (const MouseEvent&amp; e)"/>
    <METHOD name="mouseDrag (const MouseEvent&amp; e)"/>
    <METHOD name="mouseDown (const MouseEvent&amp; e)"/>
  </METHODS>
  <BACKGROUND backgroundColour="ffb4a7d6">
    <ROUNDRECT pos="8 98 584 78" cornerSize="10.00000000000000000000" fill="solid: ffcdcdcd"
               hasStroke="0"/>
    <ROUNDRECT pos="8 128 584 48" cornerSize="10.00000000000000000000" fill="solid: ffffffff"
               hasStroke="0"/>
    <RECT pos="8 128 584 22" fill="solid: ffffffff" hasStroke="0"/>
    <ROUNDRECT pos="8 186 584 184" cornerSize="10.00000000000000000000" fill="solid: ffcdcdcd"
               hasStroke="0"/>
    <ROUNDRECT pos="8 290 584 102" cornerSize="10.00000000000000000000" fill="solid: ffffffff"
               hasStroke="0"/>
    <RECT pos="8 216 584 80" fill="solid: ffffffff" hasStroke="0"/>
    <ROUNDRECT pos="8 10 584 78" cornerSize="10.00000000000000000000" fill="solid: ffcdcdcd"
               hasStroke="0"/>
    <ROUNDRECT pos="8 40 584 48" cornerSize="10.00000000000000000000" fill="solid: ffffffff"
               hasStroke="0"/>
    <RECT pos="8 40 584 24" fill="solid: ffffffff" hasStroke="0"/>
  </BACKGROUND>
  <IMAGEBUTTON name="addTagButton" id="59a453191132551" memberName="addTagButton"
               virtualName="" explicitFocusOrder="0" pos="560 144 24 24" tooltip="Add a new slice tag"
               buttonText="Add Label" connectedEdges="0" needsCallback="1" radioGroupId="0"
               keepProportions="1" resourceNormal="plus_button_up_png" opacityNormal="1.00000000000000000000"
               colourNormal="0" resourceOver="plus_button_up_png" opacityOver="1.00000000000000000000"
               colourOver="0" resourceDown="plus_button_down_png" opacityDown="1.00000000000000000000"
               colourDown="0"/>
  <LABEL name="autoGenTitleLabel" id="ea4fd442852177fd" memberName="label"
         virtualName="" explicitFocusOrder="0" pos="8 96 176 35" tooltip="Name automatically generated by current slice's tags"
         textCol="ff878787" edTextCol="ff000000" edBkgCol="0" labelText="Autogenerated Slice Title:"
         editableSingleClick="0" editableDoubleClick="0" focusDiscardsChanges="0"
         fontname="Avenir Next" fontsize="17.30000000000000071054" kerning="0.00000000000000000000"
         bold="0" italic="0" justification="33"/>
  <LABEL name="saveSectionLabel" id="bd14ff66289a517e" memberName="saveSectionLabel"
         virtualName="" explicitFocusOrder="0" pos="8 16 150 22" textCol="ff878787"
         edTextCol="ff000000" edBkgCol="0" labelText="Save" editableSingleClick="0"
         editableDoubleClick="0" focusDiscardsChanges="0" fontname="Default font"
         fontsize="15.00000000000000000000" kerning="0.00000000000000000000"
         bold="0" italic="0" justification="33"/>
  <LABEL name="waveformEditorLabel" id="d75387467bca7725" memberName="waveformEditorLabel"
         virtualName="" explicitFocusOrder="0" pos="8 192 176 21" tooltip="Import and edit sample markers here"
         textCol="ff878787" edTextCol="ff000000" edBkgCol="0" labelText="Waveform Editor"
         editableSingleClick="0" editableDoubleClick="0" focusDiscardsChanges="0"
         fontname="Avenir Next" fontsize="17.30000000000000071054" kerning="0.00000000000000000000"
         bold="0" italic="0" justification="33"/>
  <IMAGEBUTTON name="addMarkerButton" id="b164ecad590dba5f" memberName="addMarkerButton"
               virtualName="" explicitFocusOrder="0" pos="560 361 24 24" tooltip="Add a new marker to sample"
               buttonText="Add Label" connectedEdges="0" needsCallback="1" radioGroupId="0"
               keepProportions="1" resourceNormal="plus_button_up_png" opacityNormal="1.00000000000000000000"
               colourNormal="0" resourceOver="plus_button_up_png" opacityOver="1.00000000000000000000"
               colourOver="0" resourceDown="plus_button_down_png" opacityDown="1.00000000000000000000"
               colourDown="0"/>
  <TEXTBUTTON name="saveAllSlicesButton" id="fb646a76b9b9b1df" memberName="saveAllSlicesButton"
              virtualName="" explicitFocusOrder="0" pos="16 48 104 24" tooltip="Saves all slices within waveform editor based on tags describing each slice of the sample"
              bgColOff="ffb4a7d6" buttonText="Save All Slices" connectedEdges="0"
              needsCallback="1" radioGroupId="0"/>
  <TEXTBUTTON name="manualSaveButton" id="f9411bd08ba6a7b4" memberName="manualSaveButton"
              virtualName="" explicitFocusOrder="0" pos="128 48 184 24" tooltip="Manually save currently selected slice of sample with custom name"
              bgColOff="ffb4a7d6" buttonText="Manually Save Current Slice"
              connectedEdges="0" needsCallback="1" radioGroupId="0"/>
  <LABEL name="currentSliceAutogenTitle" id="b1a882bde932438c" memberName="currentSliceAutogenTitle"
         virtualName="" explicitFocusOrder="0" pos="168 104 416 19" textCol="ff878787"
         edTextCol="ff000000" edBkgCol="0" labelText="[No slice currently selected]"
         editableSingleClick="0" editableDoubleClick="0" focusDiscardsChanges="0"
         fontname="Avenir Next" fontsize="17.30000000000000071054" kerning="0.00000000000000000000"
         bold="0" italic="0" justification="33"/>
  <TEXTEDITOR name="tagRenameEditor" id="af484b5591433d4b" memberName="tagRenameEditor"
              virtualName="" explicitFocusOrder="0" pos="16 160 536 16" textcol="ffcdcdcd"
              bkgcol="ffffffff" hilitecol="ffb4a7d6" outlinecol="ffcdcdcd"
              shadowcol="ffffffff" caretcol="ffb4a7d6" initialText="rename selected tag"
              multiline="0" retKeyStartsLine="0" readonly="0" scrollbars="0"
              caret="1" popupmenu="1"/>
</JUCER_COMPONENT>

END_JUCER_METADATA
*/
#endif

//==============================================================================
// Binary resources - be careful not to edit any of these sections!

// JUCER_RESOURCE: plus_button_up_png, 4384, "../../Desktop/PLUS_BUTTON_UP.png"
static const unsigned char resource_FrontEnd_plus_button_up_png[] = { 137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,225,0,0,0,225,8,6,0,0,0,62,179,210,122,0,0,16,231,73,68,65,84,120,218,237,157,
59,175,35,213,18,70,253,47,248,183,4,32,33,65,68,66,48,17,18,9,186,1,17,71,36,35,34,18,52,34,69,36,100,68,104,72,145,144,8,124,239,242,220,58,211,83,167,118,119,219,238,118,191,214,146,90,231,101,251,
216,221,251,235,170,93,85,187,246,233,36,171,225,124,62,127,244,251,239,191,159,127,249,229,151,243,207,63,255,124,254,241,199,31,207,79,79,79,231,239,190,251,238,252,245,215,95,159,95,189,122,117,254,
234,171,175,206,95,126,249,229,229,248,226,139,47,206,159,127,254,249,229,107,252,142,191,243,56,30,207,243,120,62,175,195,235,241,186,188,190,103,90,14,207,175,191,254,122,17,198,55,223,124,115,17,13,
66,250,228,147,79,158,143,79,63,253,244,114,124,246,217,103,31,28,60,110,236,145,159,27,175,217,253,63,136,151,255,255,237,183,223,94,222,15,239,203,171,35,187,20,220,235,215,175,47,150,41,11,237,90,97,
205,117,132,72,187,239,143,247,203,251,86,152,178,57,112,251,176,44,93,235,118,139,37,91,131,48,57,186,86,147,207,245,230,205,27,69,41,235,130,57,214,247,223,127,127,25,164,31,127,252,241,93,22,174,207,
117,228,224,245,227,232,90,211,120,108,254,123,159,139,123,143,197,228,245,153,127,254,240,195,15,206,49,101,25,8,112,48,159,139,193,127,205,160,238,10,173,107,41,25,212,188,38,130,254,233,167,159,158,
131,40,127,254,249,231,249,175,191,254,58,255,253,247,223,231,127,254,249,231,252,239,191,255,158,251,224,239,60,142,199,243,60,158,31,193,30,94,151,215,231,255,240,255,186,150,238,22,129,198,243,121,
46,86,82,215,85,102,159,219,49,120,175,157,207,101,75,69,32,132,168,37,110,43,226,64,40,67,194,154,11,254,47,255,159,247,129,64,121,95,188,191,108,105,175,17,36,7,130,252,237,183,223,20,164,220,207,219,
183,111,255,195,192,236,90,172,107,6,35,214,6,203,131,21,194,34,109,9,222,47,239,155,207,207,231,184,70,148,93,11,201,231,119,36,201,77,238,38,22,97,140,240,186,150,142,239,25,180,88,77,220,193,61,193,
231,225,115,241,249,226,243,142,17,101,8,146,243,169,187,42,131,16,146,31,51,184,186,194,99,112,225,202,109,205,210,77,97,41,201,45,198,205,106,204,57,139,199,113,190,28,109,242,1,225,114,50,64,250,238,
234,33,60,42,82,176,150,123,179,118,247,88,73,82,23,156,151,177,231,81,87,85,46,243,61,18,210,4,33,198,220,193,153,23,113,7,87,120,253,16,232,193,66,198,60,114,232,220,114,254,9,120,57,34,15,4,245,153,
81,189,210,55,64,194,234,97,37,255,248,227,15,213,117,3,156,183,49,94,70,220,232,20,227,1,224,34,247,89,190,24,12,36,222,73,33,144,111,147,251,225,60,226,69,68,21,81,223,249,231,250,32,92,71,235,206,96,
238,49,116,241,99,174,71,126,75,230,131,8,233,80,228,57,174,7,129,50,71,239,198,33,88,208,23,181,235,138,79,151,243,177,80,32,48,36,198,184,118,166,54,54,26,116,137,192,128,226,219,142,24,91,115,198,184,
86,142,236,141,165,27,90,119,215,136,116,114,241,101,61,48,13,24,115,227,164,104,220,81,190,82,16,85,95,1,50,174,13,1,23,92,27,89,47,228,95,227,122,245,93,71,71,252,74,3,47,125,119,80,162,115,178,13,40,
44,199,226,245,69,178,13,220,172,104,238,199,93,177,117,215,140,138,126,19,236,219,77,252,71,78,183,101,21,113,97,85,194,66,80,149,209,119,113,16,167,243,190,253,164,53,90,83,141,240,116,92,241,255,96,
136,166,181,172,31,46,12,174,140,236,207,69,37,232,198,245,109,121,61,88,77,213,177,96,240,37,92,147,163,173,102,56,98,74,35,44,96,101,21,13,218,204,8,129,149,214,93,144,223,19,156,145,227,88,69,230,250,
173,233,8,191,55,193,63,49,173,19,30,235,250,44,53,59,110,58,163,149,19,142,105,137,234,153,113,254,199,239,248,155,145,79,35,168,184,160,149,16,157,39,78,64,107,254,23,75,140,68,130,104,194,85,121,75,
166,49,110,12,192,180,252,125,220,12,220,16,145,12,105,171,42,110,16,55,115,149,53,18,4,214,119,34,45,184,150,62,136,15,180,230,137,252,222,102,197,3,176,144,182,18,160,243,63,153,106,158,200,248,178,
39,106,79,5,76,75,128,248,251,34,215,166,49,90,65,189,152,210,168,186,17,37,104,6,96,228,94,136,142,42,196,59,4,104,249,153,76,65,43,207,172,16,255,95,5,211,18,160,75,143,100,74,90,203,221,16,226,97,171,
107,168,122,175,230,128,252,142,0,141,200,212,224,89,181,132,120,184,168,105,43,13,97,14,80,230,166,53,253,97,236,29,42,17,175,5,148,37,121,122,122,106,78,131,118,47,64,86,194,183,238,66,206,1,101,13,
115,196,221,87,214,84,161,98,78,4,46,130,200,163,137,109,222,14,83,107,26,219,51,155,134,144,53,65,33,72,30,151,252,188,187,125,49,170,15,26,251,156,139,44,13,149,53,45,3,177,219,100,60,31,152,15,46,178,
6,216,176,166,181,98,103,243,57,68,10,101,171,72,40,197,181,238,120,36,107,130,162,239,93,70,76,91,53,123,54,99,146,53,82,25,141,77,7,106,90,129,24,219,208,203,154,161,171,119,53,125,34,126,177,41,1,146,
131,201,86,144,159,73,146,138,172,29,86,94,84,6,100,51,197,222,177,178,217,64,140,108,21,214,34,182,86,230,111,66,132,173,166,172,174,138,151,45,65,27,149,150,49,89,181,0,241,155,179,8,163,66,93,100,107,
84,75,237,152,86,145,118,91,165,0,9,184,84,111,216,138,24,217,227,252,112,51,233,8,34,164,34,91,134,105,212,38,234,75,91,110,168,249,64,217,3,209,110,63,123,121,184,171,171,89,31,88,189,65,242,45,34,123,
161,170,127,94,141,91,74,9,90,101,170,69,246,4,101,150,149,91,186,248,94,23,152,227,252,198,112,67,237,146,45,123,132,190,72,217,235,91,188,171,119,149,71,177,79,168,236,153,106,217,211,98,65,26,196,86,
173,17,116,117,132,236,25,130,141,185,200,155,113,79,127,164,135,10,240,127,239,229,163,202,44,219,41,77,142,0,181,209,149,1,122,168,8,115,2,211,218,80,57,122,144,38,10,83,22,107,89,24,147,83,145,163,
80,5,37,31,150,178,200,19,83,190,127,245,234,149,87,69,14,71,213,32,138,88,201,195,19,243,252,108,101,140,28,145,170,146,102,118,107,88,89,65,59,166,201,145,33,61,145,173,33,129,155,135,89,65,230,134,
52,200,17,57,42,213,234,161,217,246,181,168,34,162,90,65,145,243,185,42,221,164,118,250,33,121,65,231,130,34,245,220,112,242,61,45,114,117,76,20,174,138,200,59,242,90,90,210,23,212,154,78,38,194,42,47,
104,145,182,200,123,170,188,33,110,234,44,43,37,172,142,17,121,9,85,52,179,173,176,200,147,78,27,248,174,231,162,19,24,139,141,117,44,156,95,158,92,83,58,73,211,224,214,170,121,89,30,86,122,135,135,226,
14,87,235,128,64,229,228,201,251,188,164,159,239,237,158,182,14,170,139,45,203,67,9,103,87,51,119,247,162,49,57,175,8,229,58,72,87,76,22,160,97,145,98,14,200,88,168,173,8,165,31,90,232,79,182,186,34,215,
137,242,194,46,218,85,132,50,76,149,87,191,105,173,97,149,27,52,2,167,8,101,152,42,160,201,113,119,110,144,32,141,40,66,25,199,221,61,74,179,43,106,110,80,17,202,117,224,126,222,229,146,86,185,65,93,81,
69,40,227,169,182,86,27,29,37,205,33,86,93,81,69,40,183,113,243,38,163,121,221,160,81,81,69,40,183,145,163,164,163,19,247,85,130,222,93,118,21,161,92,79,222,58,126,212,222,21,85,104,213,205,93,20,161,
220,6,137,251,42,213,215,43,66,182,1,206,243,65,183,56,83,132,114,59,185,150,116,112,121,83,245,4,23,239,42,66,185,157,42,231,222,219,127,166,106,237,141,73,21,69,40,183,145,83,21,177,40,190,20,224,219,
183,111,255,147,31,108,193,182,34,148,251,231,133,149,113,27,93,170,198,28,81,20,161,76,63,47,44,69,200,202,236,252,64,66,172,162,8,229,62,114,9,91,115,63,195,92,112,106,126,80,17,202,52,84,249,194,114,
227,152,156,207,224,16,69,40,247,67,55,138,42,255,222,155,164,183,94,84,17,202,188,215,235,197,126,21,185,149,5,223,27,148,81,132,242,192,224,76,46,52,117,253,160,34,148,105,201,61,73,49,116,104,172,183,
82,198,174,106,138,80,166,35,47,17,12,111,179,217,101,27,65,186,136,87,17,202,116,84,113,151,15,186,115,187,114,66,17,202,188,84,17,210,231,242,181,115,218,123,208,109,207,20,161,76,15,229,107,57,23,255,
220,129,173,50,147,76,34,69,17,202,180,228,253,237,159,35,164,213,132,145,58,82,81,132,50,45,205,52,5,130,179,167,140,34,148,249,169,82,129,23,17,230,226,210,88,249,43,138,80,166,133,197,188,217,224,81,
87,90,174,158,96,159,53,81,132,50,45,121,185,96,120,157,47,90,28,114,49,93,61,161,8,101,122,90,241,151,75,203,251,92,88,106,75,11,69,40,211,83,45,105,186,244,155,169,246,164,23,69,40,211,83,245,155,33,
29,120,202,201,67,254,32,138,80,166,39,239,105,255,188,184,55,139,16,203,40,138,80,30,35,194,75,253,104,22,161,117,163,138,80,230,33,215,143,198,226,121,69,216,128,8,49,145,99,2,85,107,60,242,117,139,
160,218,26,15,206,163,17,247,119,99,42,95,59,170,104,116,71,27,48,112,114,191,72,143,219,14,206,163,237,82,222,145,69,120,233,53,99,96,102,220,201,242,184,239,208,93,126,71,190,177,95,54,14,205,41,10,
30,36,90,66,45,225,130,34,244,142,245,14,58,11,48,112,156,19,222,127,112,30,237,212,80,7,212,46,34,172,214,56,137,209,81,121,204,117,187,204,9,171,178,53,81,132,50,61,213,166,161,151,22,23,132,72,179,
8,117,29,20,161,204,51,197,41,83,20,174,162,80,132,242,24,208,85,185,135,189,235,9,21,161,60,134,102,217,90,238,12,236,22,217,138,80,230,161,185,138,34,47,185,119,95,66,69,40,243,208,92,79,216,90,114,
47,138,80,166,229,205,155,55,47,180,118,217,44,148,77,41,108,121,168,8,101,126,216,123,34,107,237,178,41,140,205,127,21,161,60,134,170,229,33,250,123,177,23,133,109,240,21,161,204,67,149,14,116,67,24,
69,40,15,164,170,211,126,22,97,181,156,201,142,107,138,80,166,131,106,153,188,33,204,165,120,59,200,245,163,86,205,40,66,153,150,170,181,197,243,214,104,80,85,205,216,10,95,17,202,116,84,1,208,75,167,
181,160,10,157,146,191,16,69,40,211,80,229,227,47,221,183,3,114,21,149,74,69,17,202,52,84,233,137,203,102,48,93,42,127,85,20,161,76,67,115,131,208,150,8,93,220,171,8,101,58,170,197,188,165,8,177,124,46,
105,82,132,50,61,213,234,137,203,98,222,76,94,210,100,33,183,34,148,105,32,200,217,13,202,160,51,54,231,125,33,194,92,200,109,112,70,17,202,52,84,41,192,75,225,118,133,229,107,138,80,166,167,183,92,45,
83,117,77,182,114,70,17,202,237,228,74,153,23,229,106,153,150,217,20,69,40,183,145,183,200,126,81,41,147,201,43,127,157,23,42,66,153,118,62,24,1,207,83,31,249,226,186,65,140,34,148,233,174,19,249,194,
211,16,213,188,208,124,161,34,148,235,201,249,193,231,182,247,67,228,26,55,123,206,40,66,185,141,220,201,144,239,159,158,158,134,69,88,181,101,35,187,47,138,80,174,163,170,23,125,238,41,51,68,222,67,205,
84,133,34,148,235,168,82,19,232,234,52,22,246,147,203,46,41,145,83,81,132,50,142,188,126,240,185,229,253,88,170,220,134,46,169,34,148,251,92,209,23,235,7,135,168,46,50,38,86,20,161,244,147,55,126,185,
218,21,237,115,73,141,146,42,66,25,166,138,138,94,229,138,182,90,94,88,208,173,8,101,28,85,174,253,106,87,180,207,37,117,219,52,69,40,109,114,87,181,176,132,167,91,201,137,123,107,73,21,161,244,147,167,
113,205,5,188,247,90,67,247,180,95,30,246,53,136,8,54,95,221,63,100,121,242,118,216,131,107,7,199,194,60,48,7,104,236,73,186,60,220,8,17,30,5,193,124,245,198,184,60,185,127,111,179,151,204,181,228,229,
77,177,40,81,68,62,36,239,53,209,219,198,98,10,151,212,45,181,69,222,67,129,203,36,185,193,22,76,44,243,100,211,10,26,145,247,228,10,25,4,136,123,122,154,18,211,21,34,53,121,229,209,100,1,153,161,254,
51,238,232,43,242,222,10,102,109,208,199,247,52,7,185,149,55,63,107,13,69,43,120,67,11,139,91,201,123,110,107,13,229,232,228,237,35,110,174,19,189,119,110,232,134,162,114,68,170,250,234,89,230,130,99,
172,161,219,168,201,17,201,157,181,31,98,5,91,115,67,155,4,203,209,200,155,188,204,62,23,28,90,107,104,21,141,28,9,246,27,204,227,127,214,136,232,216,185,161,139,126,229,40,32,182,170,25,218,233,209,228,
253,12,237,202,38,71,128,22,47,121,58,54,75,117,204,88,242,221,32,38,166,34,123,133,114,205,108,124,56,78,75,193,228,180,74,84,154,178,144,61,82,21,105,79,186,82,226,158,245,134,249,174,96,144,70,246,
6,235,53,43,207,111,146,245,130,115,5,105,152,51,138,236,133,42,35,176,72,48,102,108,47,26,235,74,101,79,84,149,49,139,6,99,198,6,105,116,75,101,15,16,237,111,141,237,211,218,168,170,201,237,206,38,91,
39,151,105,174,206,13,29,90,115,24,110,169,37,109,178,69,40,62,169,220,208,187,91,24,206,77,149,67,225,141,155,196,151,45,81,237,39,193,216,30,181,211,238,210,180,58,16,187,210,66,182,68,54,36,171,119,
67,171,198,80,121,50,107,218,66,182,66,43,29,65,113,202,105,75,228,21,199,46,121,146,45,64,218,161,242,228,16,230,105,139,84,161,93,2,53,248,219,34,107,131,169,84,46,206,94,109,58,226,154,249,97,245,161,
56,108,219,46,107,130,213,17,149,209,216,212,60,176,69,21,230,53,80,35,107,2,131,16,227,178,74,175,157,246,0,249,195,170,248,21,63,91,100,105,90,241,139,213,231,3,239,221,221,41,34,166,86,212,200,146,
84,21,49,209,202,243,180,71,90,62,55,119,28,145,71,211,242,208,54,145,144,159,114,217,83,8,209,254,52,242,72,200,89,87,99,241,174,173,173,183,30,49,141,100,168,200,220,224,121,181,140,193,233,40,16,113,
170,132,200,239,104,33,32,50,23,85,50,254,225,61,67,215,2,59,0,183,132,168,69,148,71,90,192,232,139,116,58,34,85,14,49,78,138,115,68,121,196,28,112,87,185,192,91,233,115,15,94,191,126,237,232,145,73,162,
160,173,49,198,244,231,36,109,33,242,59,87,94,200,61,144,239,107,213,48,43,192,43,132,104,67,97,185,22,246,139,168,42,97,20,224,136,57,98,21,172,225,78,198,9,181,232,91,198,64,49,54,43,31,90,2,164,31,
146,106,235,129,59,84,37,196,56,161,46,131,146,62,162,225,88,37,192,216,208,86,149,141,76,232,87,174,169,185,68,233,131,41,77,235,6,126,136,74,152,57,136,147,103,192,70,134,96,69,78,171,12,109,247,181,
160,115,195,92,176,138,110,241,59,246,1,176,139,219,177,97,122,210,154,255,33,202,205,182,165,88,27,173,60,15,39,30,49,50,15,144,227,209,42,246,136,105,203,238,214,3,174,53,114,26,39,220,117,137,199,1,
239,135,252,95,235,198,188,138,237,202,246,28,176,193,242,181,26,12,227,150,184,9,205,190,65,92,173,49,192,239,54,221,148,105,15,243,196,174,27,34,251,130,228,123,43,248,226,252,111,33,168,43,109,93,16,
4,74,68,204,29,131,247,1,41,169,86,164,60,220,79,43,96,22,164,21,25,11,171,72,80,199,8,234,118,35,159,68,192,251,110,182,120,69,170,96,5,16,148,105,93,168,184,83,186,52,106,91,174,39,121,96,110,162,173,
27,44,215,116,117,155,116,30,29,210,20,173,9,123,215,69,53,157,177,110,88,208,29,169,167,190,235,232,136,223,168,85,140,59,40,46,140,243,197,245,69,61,153,90,180,196,23,30,13,177,0,71,249,70,224,110,57,
228,162,146,107,50,165,177,44,120,38,125,215,42,110,156,204,13,29,213,27,77,240,183,42,234,67,140,204,59,20,227,50,226,195,35,233,187,62,97,21,77,188,239,200,69,237,19,99,88,70,221,212,249,211,13,97,249,
134,174,135,129,151,29,130,200,250,34,110,113,241,25,36,12,22,162,116,114,63,164,136,240,74,226,252,182,220,206,240,76,184,105,58,90,119,78,228,158,90,98,12,87,40,118,23,118,33,241,109,224,85,68,241,125,
43,224,210,189,249,241,88,71,231,1,197,216,103,25,187,3,132,249,11,119,115,19,255,195,9,118,34,152,68,58,135,110,116,97,249,20,159,60,47,149,26,26,48,220,205,35,82,71,62,75,65,190,23,30,243,183,161,185,
94,246,50,92,106,36,47,136,14,205,125,174,83,75,144,52,23,58,18,68,147,187,194,27,115,206,66,160,120,20,142,54,233,133,22,253,99,239,234,93,65,242,51,115,72,194,239,123,179,146,220,100,8,86,133,215,48,
230,220,116,197,199,205,202,84,131,220,149,222,232,43,137,171,6,93,68,89,17,37,131,119,107,150,18,75,199,205,136,207,223,181,118,215,156,3,190,234,114,202,100,32,164,88,205,61,118,48,102,75,25,22,1,97,
226,194,18,61,68,156,75,165,66,232,227,202,255,199,114,227,34,134,224,8,150,220,242,57,227,57,88,75,91,11,202,195,4,57,214,45,203,237,247,186,194,140,142,96,44,74,125,122,122,186,8,130,255,129,56,176,
72,4,62,112,111,17,205,144,96,249,123,136,139,231,33,6,220,64,172,26,115,56,110,0,188,247,216,190,60,222,195,53,130,107,9,207,166,186,178,8,12,60,44,72,212,56,222,50,152,43,129,118,69,26,7,22,42,142,238,
255,138,199,230,191,119,5,22,71,107,113,236,53,86,157,215,71,196,22,83,203,42,193,138,97,209,178,40,111,29,248,75,29,217,90,147,247,227,102,227,10,118,217,28,184,130,4,39,162,74,103,109,194,172,220,99,
190,199,101,197,125,213,197,148,221,10,19,87,14,139,137,91,23,86,51,187,143,33,144,91,4,155,159,91,185,184,88,55,42,129,152,207,97,193,21,156,200,233,93,91,71,92,62,68,129,80,9,164,32,18,44,19,214,20,
209,32,92,14,68,132,224,248,202,207,252,141,131,199,241,120,220,71,172,48,22,141,104,44,226,55,106,185,62,254,11,5,74,133,79,91,101,156,172,0,0,0,0,73,69,78,68,174,66,96,130,0,0};

const char* FrontEnd::plus_button_up_png = (const char*) resource_FrontEnd_plus_button_up_png;
const int FrontEnd::plus_button_up_pngSize = 4384;

// JUCER_RESOURCE: plus_button_down_png, 4125, "../../Desktop/PLUS_BUTTON_DOWN.png"
static const unsigned char resource_FrontEnd_plus_button_down_png[] = { 137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,225,0,0,0,225,8,6,0,0,0,62,179,210,122,0,0,15,228,73,68,65,84,120,218,237,157,
189,110,20,75,16,133,247,45,238,219,18,128,132,4,17,9,129,35,36,18,116,3,34,86,36,22,17,9,178,8,65,36,188,129,31,98,175,206,248,214,50,212,86,207,111,207,76,247,204,87,210,17,198,216,203,110,119,159,169,
255,234,211,9,41,70,46,151,203,63,191,127,255,190,124,255,254,253,242,237,219,183,203,151,47,95,46,231,243,249,242,241,227,199,203,187,119,239,46,119,119,119,151,183,111,223,94,222,188,121,211,224,245,
235,215,151,87,175,94,53,127,218,247,244,239,250,57,253,188,126,79,191,175,215,209,235,233,117,245,250,172,52,114,120,249,249,243,103,67,140,247,239,223,55,164,17,145,158,63,127,126,197,139,23,47,26,188,
124,249,242,47,232,231,134,194,255,174,189,102,251,255,17,121,245,255,127,248,240,161,121,63,122,95,236,14,178,75,194,221,223,223,55,154,201,19,109,44,177,150,130,145,180,253,254,244,126,245,190,33,38,
82,157,200,236,147,102,105,107,183,41,154,172,4,98,10,109,173,169,207,245,240,240,0,41,145,178,68,62,214,167,79,159,154,67,250,236,217,179,89,26,174,203,116,20,244,250,134,182,54,181,159,245,255,222,101,
226,206,209,152,122,125,249,159,159,63,127,198,199,68,182,17,5,56,228,207,217,225,31,115,168,219,68,107,107,74,29,106,189,166,8,253,245,235,215,107,16,229,199,143,31,179,97,193,30,189,174,94,95,255,143,
254,191,182,166,155,66,80,251,125,253,174,180,36,166,43,178,184,111,167,195,59,214,159,243,154,74,129,16,69,45,101,182,230,34,89,14,146,138,160,122,95,122,127,94,211,142,33,164,32,66,254,250,245,11,66,
34,243,229,241,241,241,95,29,204,182,198,26,115,24,165,109,164,121,164,133,74,32,219,88,232,125,235,243,235,115,140,33,101,91,67,234,243,115,146,144,73,230,166,52,194,16,226,181,53,157,190,214,161,149,
214,172,145,116,125,208,231,210,231,179,207,59,132,148,70,72,173,39,230,42,210,43,10,201,15,57,92,109,226,233,112,201,148,219,35,233,250,160,220,162,61,172,134,172,153,253,156,214,139,211,134,252,37,102,
114,234,128,116,61,213,141,120,170,72,169,213,196,92,10,74,93,104,93,134,174,35,166,42,210,248,123,74,72,43,8,49,228,9,46,191,232,168,26,111,138,134,52,63,178,111,109,181,254,10,120,113,34,15,36,170,207,
180,234,149,174,3,98,90,79,90,18,98,77,199,16,43,195,30,116,144,241,0,162,77,238,210,124,118,24,148,120,87,10,1,18,229,131,172,8,171,34,234,90,127,237,143,136,203,105,221,153,200,247,232,219,124,243,245,
148,223,130,52,203,70,88,251,34,207,182,31,10,148,113,122,43,23,5,11,186,162,118,109,242,65,144,245,11,4,250,200,104,123,71,106,163,210,160,139,5,6,32,95,61,100,76,249,140,182,87,156,236,202,210,13,169,
167,171,69,58,75,41,25,3,79,144,27,48,228,193,169,162,113,78,121,161,34,82,117,21,32,203,180,81,192,101,175,213,44,123,129,242,175,182,95,93,251,200,137,47,52,240,210,245,4,37,199,87,23,164,241,186,34,
217,4,110,10,242,253,244,84,76,61,53,173,162,159,67,93,47,44,167,155,210,138,50,97,97,194,70,162,170,140,174,205,17,57,241,251,246,147,214,72,185,26,102,233,208,241,191,178,40,154,150,210,126,50,97,100,
202,112,120,247,89,125,163,253,77,89,61,210,154,176,99,195,224,139,153,38,28,214,253,167,52,76,3,70,90,145,160,205,130,162,192,74,234,41,168,239,43,56,195,33,61,14,228,235,167,220,17,125,159,4,127,102,
73,45,184,245,245,81,106,118,220,116,70,42,39,108,110,9,236,89,208,255,211,247,244,111,28,70,32,19,52,34,34,126,98,6,73,249,127,180,24,1,15,27,194,21,89,75,164,49,38,6,96,82,246,190,204,12,186,218,65,
170,153,56,138,27,216,195,28,102,13,20,17,172,107,33,57,108,160,175,6,53,229,39,234,251,12,43,238,17,53,210,70,4,196,255,3,185,252,68,157,47,102,162,118,84,192,164,8,40,123,159,131,5,198,34,21,212,51,
151,6,214,13,40,65,35,0,3,114,212,158,66,196,25,4,164,252,12,44,153,216,135,136,255,87,193,164,8,72,235,17,200,137,84,187,155,136,120,216,234,26,85,189,71,62,160,190,199,164,51,176,84,143,98,138,136,135,
139,154,166,210,16,228,0,193,26,185,196,20,17,15,149,136,71,3,130,45,113,62,159,147,110,208,238,9,168,78,248,212,83,8,31,16,148,224,35,238,190,178,38,10,21,107,33,100,34,112,48,192,22,77,194,254,76,238,
186,214,212,174,103,38,13,1,74,43,252,246,231,82,127,223,221,189,24,209,7,181,123,206,57,8,160,132,202,154,148,130,216,109,50,94,31,152,90,80,80,18,82,29,59,213,231,16,85,40,27,69,66,85,92,203,198,131,
210,176,203,136,105,170,102,143,13,7,165,182,65,121,165,81,117,160,38,21,136,97,12,61,40,25,154,234,29,185,79,138,95,84,69,64,229,96,188,22,212,223,149,36,101,163,65,13,157,23,145,2,169,166,216,219,58,
155,9,196,128,154,145,234,204,175,130,132,169,161,172,108,44,168,61,80,99,202,164,104,2,202,110,246,36,180,10,117,54,21,212,134,168,213,78,110,149,210,110,69,18,80,1,151,232,13,83,17,3,246,232,31,86,147,
142,224,110,8,176,7,84,81,95,154,50,67,217,64,176,7,216,184,125,111,229,201,92,45,166,63,48,122,131,202,183,176,129,96,207,133,222,197,152,165,42,65,139,84,53,27,7,142,96,150,110,126,215,133,212,177,127,
99,152,161,96,175,208,92,36,111,245,109,62,213,59,202,163,48,39,20,28,173,237,105,179,32,141,200,22,245,8,178,81,96,239,240,69,222,58,247,154,143,180,42,1,47,151,203,63,145,90,102,82,26,56,202,124,154,
72,1,173,74,66,159,192,164,54,20,28,61,72,99,133,41,155,141,44,52,231,148,205,1,71,42,105,243,68,92,45,101,225,29,83,125,125,119,119,199,198,128,195,119,90,88,96,114,245,196,188,254,206,134,0,42,105,86,
210,134,145,22,100,98,26,56,50,148,158,240,218,80,129,155,213,180,32,137,121,112,116,68,221,67,139,221,107,17,69,68,209,130,0,60,93,205,237,181,161,106,167,87,201,11,178,1,0,196,190,97,246,59,45,124,117,
140,21,174,178,1,0,60,193,247,210,42,125,161,90,211,108,36,140,242,130,44,60,0,221,121,67,153,169,139,116,74,80,29,3,192,176,193,80,217,58,44,188,211,201,0,223,114,160,192,24,23,235,148,91,83,154,101,
104,112,170,107,158,5,47,163,211,219,44,20,136,88,182,54,204,122,165,153,190,102,122,90,185,155,205,186,108,15,149,112,182,57,51,123,22,13,201,121,72,8,198,167,43,178,5,104,212,164,232,3,50,20,106,67,
66,48,190,205,105,178,73,234,235,68,245,194,52,237,66,66,208,143,40,175,62,169,215,144,220,32,36,4,211,16,5,52,133,217,185,65,5,105,88,96,72,8,166,245,26,142,54,73,189,41,74,110,16,18,130,113,144,249,
57,203,36,37,55,8,9,65,254,61,26,28,37,245,33,86,76,81,72,8,242,20,117,15,54,73,125,223,32,81,81,72,8,242,68,73,7,39,238,73,208,67,66,144,7,254,234,248,65,119,87,68,161,85,46,119,129,132,96,58,162,84,
95,39,9,117,13,176,247,7,185,226,12,18,130,124,181,164,189,237,77,209,47,176,144,144,16,228,107,246,237,157,63,19,141,246,102,33,33,33,200,183,87,214,20,31,18,240,241,241,241,95,255,195,20,108,67,66,144,
191,160,59,121,121,76,164,54,229,35,178,136,144,16,228,247,11,67,18,170,51,219,255,160,66,172,44,34,36,4,121,75,216,146,247,25,250,130,83,242,131,144,16,44,151,47,12,47,142,241,249,12,129,5,132,132,96,
153,253,186,185,98,219,39,233,169,23,133,132,96,217,253,186,185,175,194,143,178,208,215,4,101,32,33,88,49,56,227,11,77,233,31,132,132,32,47,252,76,82,41,58,113,140,74,25,72,8,86,130,111,17,52,107,51,57,
101,91,132,100,225,32,33,88,110,238,204,205,116,110,58,39,32,33,88,127,207,174,229,107,254,238,65,174,61,131,132,96,25,248,92,252,117,2,91,164,38,229,68,178,104,144,16,228,133,191,223,254,26,33,141,28,
70,213,145,178,104,144,16,172,148,166,16,225,152,41,3,9,193,250,51,103,174,36,244,197,165,214,249,203,162,65,66,144,23,106,230,245,10,79,117,165,97,247,4,11,6,9,193,242,93,246,102,117,222,140,56,100,51,
33,33,88,47,97,223,140,64,84,174,130,22,38,72,8,182,105,105,106,230,205,68,119,210,179,96,144,16,44,191,111,150,14,60,249,228,33,37,107,144,16,172,71,194,166,185,215,147,80,154,145,197,130,132,96,29,18,
54,245,163,158,132,212,141,66,66,176,30,9,213,60,15,9,59,160,200,177,2,85,37,194,239,155,5,213,74,4,181,200,127,224,247,78,85,52,152,163,29,4,244,243,34,193,52,104,29,25,151,18,147,176,153,53,67,96,102,
216,98,129,121,192,92,126,130,127,176,55,23,135,250,20,5,163,239,209,132,104,194,141,73,200,19,235,15,116,112,240,9,231,3,2,166,3,106,13,9,163,30,39,22,139,232,40,88,103,223,26,159,144,178,53,72,8,182,
139,53,52,35,46,20,34,133,132,144,16,108,152,162,160,139,2,18,130,237,146,245,205,29,246,244,19,66,66,176,113,217,154,159,12,204,102,66,66,176,114,23,133,111,185,231,94,66,72,8,86,238,39,76,181,220,179,
104,144,16,228,197,195,195,195,13,215,154,203,66,117,41,5,35,15,33,33,88,30,186,123,194,115,173,185,20,134,225,191,144,16,172,131,104,228,161,248,119,115,23,5,99,240,33,33,88,174,30,57,121,71,33,23,194,
64,66,176,60,162,58,237,43,9,105,103,130,132,96,121,248,11,97,154,226,109,19,95,63,202,134,66,66,176,124,142,240,122,53,154,36,170,154,97,20,62,36,4,249,16,5,64,155,73,107,38,81,232,84,249,11,22,15,18,
130,60,136,242,241,205,244,109,19,229,42,34,150,178,120,144,16,44,151,158,104,46,131,105,75,100,175,178,120,144,16,228,65,242,130,208,20,9,233,43,132,132,96,217,62,194,144,132,210,124,116,83,64,66,176,
78,100,180,105,230,245,226,91,154,40,228,134,132,32,15,20,228,108,7,101,196,51,93,206,123,67,66,95,200,77,112,6,18,130,60,136,82,128,77,225,118,36,148,175,65,66,176,114,185,154,23,166,38,67,66,176,252,
94,253,85,174,230,37,165,54,89,72,72,8,166,193,95,145,125,83,41,227,197,119,254,226,23,66,66,144,215,31,180,128,231,169,75,252,230,210,81,1,9,65,190,125,82,190,240,212,39,248,133,144,16,44,183,79,205,
216,251,62,241,53,110,204,156,129,132,96,26,252,36,67,125,125,62,159,251,73,24,141,101,83,118,159,69,133,132,96,126,189,232,117,166,76,159,248,59,212,216,96,72,8,230,239,145,120,117,26,42,186,79,206,155,
164,138,156,178,176,144,16,76,235,31,188,142,188,31,42,81,110,3,147,20,18,130,121,166,232,77,255,96,159,176,201,144,16,108,100,138,118,153,164,68,73,33,33,152,22,21,29,101,138,166,70,94,80,208,13,9,193,
48,68,185,246,209,166,40,38,41,36,4,211,224,167,170,153,38,60,77,21,159,184,167,150,20,18,130,110,120,55,46,217,192,139,54,172,31,186,215,192,34,216,250,147,251,67,202,125,56,158,230,138,252,64,31,160,
97,38,105,57,68,84,65,48,4,44,3,126,126,111,114,150,204,88,241,237,77,214,148,200,162,3,240,55,252,93,19,157,99,44,114,152,164,92,169,13,192,223,205,187,89,114,131,41,145,99,233,157,77,42,104,0,72,87,
200,136,128,50,79,79,57,133,0,13,0,49,124,231,81,182,128,76,223,252,25,110,244,5,224,143,22,244,220,208,28,223,211,18,226,71,121,51,42,31,160,5,127,77,27,97,49,85,252,157,219,104,67,112,116,248,235,35,
38,215,137,206,245,13,185,80,20,28,17,81,125,245,34,190,224,16,109,200,53,106,224,136,240,147,181,87,209,130,41,223,144,33,193,224,104,240,151,188,44,238,11,246,245,26,82,69,3,142,94,29,179,104,68,116,
168,111,72,211,47,56,10,68,182,104,24,218,105,109,241,247,25,146,192,7,71,129,119,199,22,169,142,25,42,254,105,96,142,41,27,5,246,10,149,107,122,229,35,156,182,18,57,167,81,162,146,148,5,56,74,145,118,
214,78,137,57,253,134,254,169,64,144,6,236,17,145,229,151,165,95,112,169,32,141,124,70,54,14,236,117,108,197,102,193,152,161,179,104,168,43,5,123,175,140,217,52,24,51,52,72,131,89,10,246,106,134,246,94,
121,189,149,68,213,228,76,103,3,123,152,227,83,180,25,218,215,115,104,102,41,37,109,160,70,168,248,36,50,67,103,143,48,92,90,162,28,138,222,56,155,10,106,67,100,217,13,186,105,119,107,73,77,32,166,211,
2,212,4,175,72,138,55,67,163,193,80,222,153,37,109,1,106,79,71,168,56,229,84,147,248,142,99,90,158,64,13,80,218,33,178,228,68,204,83,141,18,133,118,201,31,130,82,33,87,202,23,103,23,155,142,24,227,31,
70,31,74,96,211,65,13,249,192,170,252,192,148,68,97,94,2,53,160,196,64,76,42,189,118,218,131,40,127,24,21,191,202,206,230,0,128,210,38,166,153,6,44,62,31,56,247,118,39,139,152,82,81,3,74,171,136,177,81,
158,167,61,74,202,230,214,19,135,3,1,214,70,202,66,171,34,33,159,179,237,201,136,200,124,26,176,246,156,152,232,44,206,186,218,186,246,136,169,37,67,57,32,96,105,200,242,74,41,131,211,81,68,17,167,136,
136,250,158,70,8,112,80,192,154,201,248,213,103,134,150,34,186,1,56,69,68,52,34,88,83,3,218,92,164,211,17,37,202,33,218,162,224,35,130,53,124,192,93,229,2,167,74,151,121,112,127,127,207,1,2,89,162,160,
169,51,38,247,231,132,164,137,168,239,209,121,1,230,230,1,83,53,204,16,112,4,17,25,40,12,114,85,194,64,192,1,62,98,20,172,209,147,140,90,83,48,6,234,124,72,17,80,243,144,96,91,135,232,9,21,17,209,22,148,
3,6,186,96,3,199,34,2,218,133,182,176,108,96,66,63,50,77,201,37,130,190,28,96,234,1,126,136,74,152,37,196,22,143,128,13,24,50,146,34,85,134,182,251,90,208,165,69,190,96,20,221,210,247,116,15,0,7,16,164,
252,63,145,178,218,177,20,165,73,42,207,163,133,23,25,229,7,112,24,153,11,234,221,150,221,245,3,150,26,57,181,5,167,47,241,120,249,191,212,131,185,136,235,202,246,28,176,145,230,75,13,24,230,238,139,253,
67,228,74,157,1,125,175,234,161,76,123,240,19,219,102,8,7,246,56,193,23,252,191,141,68,117,165,169,13,17,65,21,17,227,198,224,125,64,41,169,84,164,220,204,79,42,96,54,148,84,100,204,180,34,37,111,117,
67,17,240,174,135,173,172,34,88,80,128,40,40,147,218,40,123,82,210,26,85,95,235,145,30,162,169,7,172,246,180,184,75,58,143,46,74,83,164,28,246,182,137,74,58,163,108,168,161,219,82,79,93,251,200,137,175,
84,43,218,19,84,38,12,254,98,121,81,79,185,22,41,242,153,69,163,88,0,167,188,18,209,211,178,207,68,85,174,9,2,108,95,112,221,181,87,246,224,148,111,200,169,174,52,193,159,170,168,55,50,202,239,128,140,
219,144,79,22,73,215,254,152,86,36,241,190,35,19,181,139,140,166,25,49,83,151,79,55,152,230,235,219,15,2,47,59,20,145,172,43,226,102,155,175,67,66,187,84,254,58,79,91,223,148,217,105,150,137,30,154,156,
214,157,139,229,158,82,100,52,83,136,219,133,231,223,247,103,197,247,169,128,75,251,225,167,159,229,116,30,144,140,93,154,177,125,64,228,191,144,107,28,6,69,48,21,233,236,123,208,153,230,131,124,200,181,
85,170,239,192,232,105,110,145,58,6,20,223,118,181,247,249,122,222,202,160,213,8,185,17,155,208,220,101,58,65,200,152,120,67,214,204,8,42,139,130,211,134,116,138,70,244,15,125,170,183,9,169,191,203,135,
220,107,85,142,130,85,102,53,12,89,155,54,249,244,176,34,213,128,204,74,111,116,149,196,69,135,206,162,172,34,101,173,145,86,61,140,244,249,219,218,110,204,26,232,79,76,78,36,155,136,72,214,205,61,244,
48,122,77,105,26,65,196,148,9,91,74,78,82,154,91,38,162,17,78,193,146,41,159,211,126,71,218,146,209,130,200,106,132,28,106,150,249,241,123,109,98,218,68,48,53,165,158,207,231,134,16,250,63,114,152,181,
34,131,204,64,105,53,249,112,122,0,232,189,219,245,229,246,30,198,16,46,69,60,134,234,34,155,136,14,158,52,136,213,56,78,57,204,17,65,219,36,53,72,67,25,218,255,151,253,172,255,247,54,193,12,169,230,216,
49,90,93,175,47,18,83,76,141,20,41,210,98,210,104,158,148,83,15,254,86,240,218,90,121,63,61,108,232,96,71,170,19,153,130,10,78,88,149,78,105,196,140,204,99,125,45,147,85,230,43,38,38,178,91,98,202,148,
147,198,148,89,103,90,211,155,143,70,144,41,132,245,191,27,153,184,210,110,170,4,146,63,39,13,14,225,16,228,244,52,214,81,38,159,72,33,162,42,144,34,146,72,51,73,155,138,52,34,174,32,18,137,112,250,83,
127,215,191,9,250,57,253,188,204,71,105,97,105,52,69,99,69,126,162,150,229,201,127,193,75,255,147,58,120,68,80,0,0,0,0,73,69,78,68,174,66,96,130,0,0};

const char* FrontEnd::plus_button_down_png = (const char*) resource_FrontEnd_plus_button_down_png;
const int FrontEnd::plus_button_down_pngSize = 4125;

// JUCER_RESOURCE: minus_button_up_png, 4562, "../../Desktop/Simpler Assets/MINUS_BUTTON_UP.png"
static const unsigned char resource_FrontEnd_minus_button_up_png[] = { 137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,225,0,0,0,225,8,6,0,0,0,62,179,210,122,0,0,17,153,73,68,65,84,120,218,237,157,
73,143,35,69,19,134,253,47,248,183,236,32,177,239,203,176,74,92,16,7,78,180,184,140,56,113,65,35,174,136,11,55,78,140,56,14,18,18,2,127,122,170,191,240,212,100,71,86,149,237,42,187,150,231,145,74,211,
227,182,221,229,114,190,21,145,17,145,145,187,157,204,134,71,143,30,61,245,219,111,191,237,127,254,249,231,253,79,63,253,180,255,225,135,31,246,55,55,55,251,111,191,253,118,255,229,151,95,238,239,221,
187,183,255,224,131,15,246,111,191,253,118,115,188,250,234,171,251,87,94,121,165,249,55,30,227,247,60,143,231,243,58,94,207,251,240,126,188,47,239,239,149,150,205,243,203,47,191,52,194,248,234,171,175,
26,209,32,164,231,159,127,254,112,188,240,194,11,205,241,242,203,47,63,113,240,188,161,71,249,218,120,207,246,223,65,188,252,253,175,191,254,186,57,31,206,203,111,71,86,41,184,251,247,239,55,150,169,20,
218,177,194,154,234,8,145,182,207,143,243,229,188,21,166,44,14,220,62,44,75,219,186,157,98,201,230,32,76,142,182,213,228,115,61,120,240,64,81,202,188,96,142,245,221,119,223,53,131,244,233,167,159,62,203,
194,117,185,142,28,188,127,28,109,107,26,207,45,127,223,229,226,158,99,49,121,127,230,159,223,127,255,189,115,76,185,14,4,56,152,207,197,224,63,102,80,183,133,214,182,148,12,106,222,19,65,255,248,227,
143,135,32,202,31,127,252,177,255,243,207,63,247,127,253,245,215,254,239,191,255,222,255,243,207,63,251,46,248,61,207,227,249,188,142,215,71,176,135,247,229,253,249,59,252,189,182,165,59,69,160,241,122,
94,139,149,212,117,149,201,231,118,12,222,99,231,115,165,165,34,16,66,212,18,183,21,113,32,148,62,97,77,5,127,151,191,207,121,32,80,206,139,243,43,45,237,49,130,228,64,144,191,254,250,171,130,148,243,
121,248,240,225,55,12,204,182,197,58,102,48,98,109,176,60,88,33,44,210,146,224,124,57,111,62,63,159,227,24,81,182,45,36,159,223,145,36,39,185,155,88,132,33,194,107,91,58,126,102,208,98,53,113,7,215,4,
159,135,207,197,231,139,207,59,68,148,33,72,174,167,238,170,244,66,72,126,200,224,106,11,143,193,133,43,183,52,75,55,134,165,36,183,24,55,171,33,215,44,158,199,245,114,180,201,19,132,203,201,0,233,186,
171,135,240,168,72,193,90,174,205,218,157,99,37,73,93,112,93,134,94,71,93,85,105,230,123,36,164,9,66,12,185,131,51,47,226,14,174,240,186,33,208,131,133,140,121,100,223,181,229,250,19,240,114,68,110,8,
234,51,163,122,165,107,128,132,213,195,74,254,254,251,239,170,235,4,184,110,67,188,140,184,209,41,198,13,192,151,220,101,249,98,48,144,120,39,133,64,190,77,206,135,235,136,23,17,85,68,93,215,159,239,7,
225,58,90,87,6,115,143,190,47,63,230,122,228,183,100,58,136,144,246,69,158,227,251,32,80,230,232,93,56,4,11,186,162,118,109,241,233,114,94,22,10,4,250,196,24,223,157,169,141,133,6,93,34,48,160,248,150,
35,198,218,156,49,190,43,71,246,194,210,13,181,187,107,68,58,249,242,101,62,48,13,24,114,227,164,104,220,81,62,83,16,85,87,1,50,174,13,1,23,92,27,153,47,228,95,227,251,234,250,30,29,241,51,13,188,116,
221,65,137,206,201,50,160,176,28,139,215,21,201,54,112,51,163,185,31,119,197,218,93,51,42,250,77,176,47,55,241,31,57,221,154,85,196,133,85,9,87,130,170,140,174,47,7,113,58,239,91,79,90,163,54,213,8,79,
199,21,255,23,134,104,90,205,250,225,194,224,202,200,250,92,84,130,110,124,191,53,175,7,171,169,58,174,24,124,9,215,100,107,171,25,182,152,210,8,11,152,89,69,131,54,19,66,96,165,118,23,228,113,130,51,
178,29,171,200,92,191,54,29,225,113,19,252,35,83,187,224,177,174,207,82,179,237,166,51,106,57,225,152,150,168,158,9,231,127,60,198,239,140,124,26,65,197,5,205,132,232,60,113,4,106,243,191,88,98,36,18,
68,19,174,204,91,50,141,113,98,0,166,230,239,227,102,224,134,136,148,144,182,202,226,6,113,51,87,89,3,65,96,93,23,210,130,107,233,130,248,64,109,158,200,227,54,43,238,129,133,180,153,0,157,255,201,88,
243,68,198,151,61,81,59,42,96,106,2,196,223,23,57,54,141,81,11,234,197,148,70,213,13,40,65,51,0,35,231,66,116,84,33,158,33,64,203,207,100,12,106,121,102,133,248,255,42,152,154,0,93,122,36,99,82,91,238,
134,16,55,91,93,67,213,123,54,7,228,49,2,52,34,99,131,103,85,19,226,230,162,166,181,52,132,57,64,153,154,218,244,135,177,183,169,68,188,22,80,174,201,205,205,77,117,26,180,122,1,178,18,190,118,23,114,
14,40,115,152,35,174,190,178,38,11,21,115,33,112,17,68,46,77,108,243,182,153,90,211,216,158,217,52,132,204,9,10,65,202,113,201,255,87,183,47,70,246,65,99,159,115,145,107,67,101,77,205,64,172,54,25,207,
7,230,131,139,204,1,54,172,169,173,216,89,124,14,145,66,217,44,18,74,113,173,59,30,201,156,160,232,123,149,17,211,90,205,158,205,152,100,142,100,70,99,209,129,154,90,32,198,54,244,50,103,232,234,157,77,
159,136,95,44,74,128,228,96,74,43,200,255,73,146,138,204,29,86,94,100,6,100,49,197,222,177,178,217,64,140,44,21,214,34,214,86,230,47,66,132,181,166,172,174,138,151,37,65,27,149,154,49,153,181,0,241,155,
75,17,70,133,186,200,210,200,150,218,49,173,34,237,54,75,1,18,112,201,78,216,138,24,89,227,252,112,49,233,8,34,164,34,75,134,105,212,34,234,75,107,110,168,249,64,89,3,209,110,191,244,242,112,87,103,179,
62,48,59,65,242,45,34,107,33,171,127,158,141,91,74,9,90,102,170,69,214,4,101,150,153,91,122,245,189,46,48,199,229,137,225,134,218,37,91,214,8,125,145,74,175,239,234,93,189,179,60,138,125,66,101,205,100,
203,158,174,22,164,65,108,217,26,65,87,71,200,154,33,216,88,22,121,51,238,233,143,116,81,1,62,122,244,232,169,204,44,219,41,77,182,0,181,209,153,1,186,168,8,203,4,166,181,161,178,245,32,77,20,166,92,173,
101,97,76,78,69,182,66,22,148,188,88,202,162,156,152,242,243,189,123,247,252,86,100,115,100,13,162,136,149,92,60,49,207,255,173,140,145,45,146,85,210,76,110,13,51,43,104,199,52,217,50,164,39,74,107,72,
224,230,98,86,144,185,33,13,114,68,182,74,182,122,104,178,125,45,178,136,168,86,80,100,191,207,74,55,169,157,190,72,94,208,185,160,72,62,55,28,125,79,139,178,58,38,10,87,69,228,150,114,45,45,233,11,106,
77,71,19,97,150,23,180,72,91,228,49,89,222,16,55,117,146,149,18,86,199,136,220,133,42,154,201,86,88,148,147,78,27,248,138,228,148,53,165,163,52,13,174,173,154,23,145,187,16,168,28,61,121,95,46,233,231,
103,187,167,137,212,161,132,179,173,153,179,123,209,152,156,23,57,14,210,21,163,5,104,88,164,88,6,100,44,212,22,233,134,22,250,163,173,174,40,235,68,121,99,23,237,138,244,147,229,213,79,90,107,152,229,
6,109,93,33,210,79,22,208,228,56,59,55,72,144,70,68,134,113,118,143,210,210,21,53,55,40,114,28,184,159,103,185,164,89,110,80,87,84,100,56,217,214,106,131,163,164,101,136,85,87,84,228,52,78,222,100,180,
92,55,104,84,84,228,52,202,40,233,224,196,125,150,160,119,151,93,145,227,41,183,142,31,180,119,69,22,90,117,115,23,145,211,32,113,159,165,250,58,69,200,54,192,229,124,208,45,206,68,78,167,172,37,237,93,
222,148,189,192,197,187,34,167,147,229,220,59,251,207,100,173,189,49,169,34,114,26,101,170,34,22,197,167,2,124,248,240,225,55,229,147,45,216,22,57,127,94,152,25,183,193,165,106,204,17,69,100,252,121,97,
42,66,150,225,151,79,36,196,42,34,231,81,150,176,85,247,51,44,11,78,205,15,138,140,67,150,47,76,55,142,41,243,25,28,34,114,62,116,163,200,242,239,157,73,122,235,69,69,198,165,119,191,138,178,149,5,63,
27,148,17,25,143,222,224,76,89,104,234,250,65,145,113,41,123,146,98,232,208,88,103,165,140,93,213,68,198,163,92,34,24,222,102,181,203,54,130,116,17,175,200,120,100,113,151,39,186,115,187,114,66,100,90,
178,8,233,161,124,173,220,123,208,109,207,150,193,127,255,253,231,69,88,16,148,175,149,185,248,67,7,182,204,76,50,137,20,145,113,41,247,183,63,68,72,179,9,35,117,164,34,50,46,213,52,5,130,179,167,140,
200,244,100,169,192,70,132,101,113,105,172,252,21,145,113,97,49,111,105,240,168,43,77,87,79,176,207,154,136,140,75,185,92,48,188,206,59,45,14,17,161,171,39,68,198,167,22,127,105,90,222,151,133,165,182,
180,16,25,159,108,73,83,211,111,38,219,147,94,68,198,39,235,55,67,58,112,87,38,15,249,133,136,140,79,185,167,253,97,113,111,41,66,44,163,136,92,70,132,77,253,104,41,66,235,70,151,65,89,182,102,25,219,
252,41,235,71,99,241,188,34,172,64,132,152,200,49,129,170,83,143,103,158,121,102,240,241,236,179,207,30,254,125,238,185,231,154,47,139,232,217,139,47,190,184,127,233,165,151,14,17,236,215,94,123,109,255,
250,235,175,239,63,250,232,163,253,199,31,127,188,255,244,211,79,155,227,179,207,62,219,191,255,254,251,77,81,48,191,163,58,35,142,79,62,249,164,121,206,231,159,127,222,60,143,131,159,249,124,95,124,241,
197,19,143,115,240,124,222,155,247,249,240,195,15,155,247,124,239,189,247,246,239,188,243,206,254,173,183,222,218,191,241,198,27,205,121,112,62,156,27,231,200,249,114,222,241,57,218,215,129,191,99,196,
253,118,76,149,109,100,248,126,116,71,43,48,112,202,126,145,151,62,248,46,56,16,29,3,159,227,205,55,223,108,132,192,205,18,81,188,251,238,187,141,64,16,32,130,225,64,60,113,180,133,24,7,130,204,126,230,
136,231,199,235,67,132,188,127,91,136,156,7,231,195,185,33,200,50,192,87,246,217,180,93,202,45,165,8,155,94,51,6,102,134,93,172,57,28,12,246,56,66,152,136,33,14,196,193,129,80,202,3,177,114,244,61,22,
7,131,35,222,47,142,182,232,226,24,122,238,70,221,111,41,111,236,205,198,161,229,29,140,39,201,60,44,225,16,43,201,81,138,115,172,163,253,190,237,191,119,236,185,106,9,143,20,161,119,172,91,232,44,192,
192,57,103,78,56,229,145,13,246,99,230,160,167,28,167,158,43,215,209,78,13,183,164,91,104,103,107,156,68,228,50,34,108,230,132,89,217,154,136,140,79,182,105,104,211,226,130,72,88,41,66,93,7,145,105,166,
56,105,138,194,85,20,34,151,1,93,165,123,216,187,158,80,228,50,84,203,214,202,206,192,110,145,45,50,13,213,85,20,229,146,123,247,37,20,153,134,234,122,194,218,146,123,17,25,151,7,15,30,220,209,90,179,
89,40,155,82,216,242,80,100,122,216,123,162,212,90,179,41,140,205,127,69,46,67,214,242,16,253,221,217,139,194,54,248,34,211,144,165,3,221,16,70,228,130,100,117,218,7,17,102,203,153,236,184,38,50,30,84,
203,148,27,194,52,197,219,65,89,63,106,213,140,200,184,100,173,45,14,91,163,65,86,53,99,43,124,145,241,200,2,160,77,167,181,32,11,157,146,191,16,145,113,200,242,241,77,247,237,128,92,69,166,82,17,25,135,
44,61,209,108,6,211,38,243,87,69,100,28,170,27,132,214,68,232,226,94,145,241,200,22,243,166,34,196,242,185,164,73,100,124,178,213,19,205,98,222,146,114,73,147,133,220,34,227,64,144,179,29,148,65,103,108,
206,123,71,132,101,33,183,193,153,101,97,27,252,249,146,165,0,155,194,237,12,203,215,150,195,191,255,254,171,240,22,66,103,185,90,73,214,53,217,202,153,249,90,62,69,56,127,202,74,153,59,229,106,37,53,
179,41,186,159,114,26,229,22,217,119,42,101,74,202,149,191,206,11,21,161,140,59,31,140,128,231,174,139,210,116,186,65,140,34,148,211,201,242,239,187,62,178,121,161,249,66,145,227,41,243,131,135,182,247,
125,148,53,110,246,156,17,57,141,178,147,33,63,223,220,220,244,139,48,107,203,70,118,95,68,142,35,171,23,61,244,148,233,163,220,67,205,84,133,200,113,100,169,9,116,181,27,10,251,201,149,46,41,145,83,17,
25,70,185,126,240,208,242,126,40,89,110,67,151,84,228,60,87,244,206,250,193,62,74,83,202,255,49,177,50,15,76,81,204,151,114,227,151,163,93,209,46,151,212,40,169,34,148,126,178,168,232,81,174,104,173,229,
133,5,221,138,80,134,145,229,218,143,118,69,187,92,82,183,77,155,143,8,21,226,252,40,187,170,133,37,220,157,74,153,184,183,150,84,17,74,55,229,52,174,186,128,247,92,107,232,158,246,138,80,238,82,110,135,
221,187,118,112,40,204,3,203,0,141,61,73,231,37,68,197,56,15,202,254,189,213,94,50,199,82,46,111,138,69,137,34,242,36,229,94,19,157,109,44,198,112,73,221,82,91,228,49,20,184,140,146,27,172,193,196,178,
156,108,90,65,35,242,152,178,66,6,1,226,158,238,198,196,116,133,72,78,185,242,104,180,128,76,95,255,25,119,244,21,121,108,5,75,109,208,199,119,55,5,101,43,111,254,175,53,20,173,224,9,45,44,78,165,220,
115,91,107,40,91,167,220,62,226,228,58,209,115,231,134,110,40,42,91,36,171,175,158,100,46,56,196,26,186,141,154,108,145,178,179,246,69,172,96,109,110,104,147,96,217,26,229,38,47,147,207,5,251,214,26,90,
69,35,91,130,253,6,203,241,63,105,68,116,232,220,208,69,191,178,21,16,91,214,12,109,119,105,202,253,12,237,202,38,91,128,22,47,229,116,108,146,234,152,161,148,119,131,152,152,138,172,21,202,53,75,227,
195,177,187,22,76,78,179,68,165,41,11,89,35,89,145,246,168,43,37,206,89,111,88,222,21,12,210,200,218,96,33,123,230,249,141,178,94,112,170,32,13,115,70,145,181,144,101,4,174,18,140,25,218,139,198,186,82,
89,19,89,101,204,85,131,49,67,131,52,186,165,178,6,136,246,215,198,246,110,110,100,213,228,118,103,147,165,83,150,105,206,206,13,237,91,115,24,110,169,37,109,178,68,40,62,201,220,208,179,91,24,78,77,150,
67,225,196,77,226,203,146,200,246,147,96,108,15,218,105,247,218,212,58,16,187,210,66,150,68,105,72,102,239,134,102,141,161,202,201,172,105,11,89,10,181,116,4,197,41,187,37,81,174,56,118,201,147,44,1,210,
14,153,39,135,48,119,75,36,11,237,18,168,193,223,22,153,27,76,165,202,226,236,217,166,35,142,153,31,102,31,138,195,253,44,100,78,176,58,34,51,26,139,154,7,214,200,194,188,6,106,100,78,96,16,98,92,102,
233,181,221,26,32,127,152,21,191,226,103,139,92,155,90,252,98,246,249,192,115,119,119,138,136,169,21,53,114,77,178,138,152,104,229,185,91,35,53,159,155,59,142,200,165,169,121,104,139,72,200,143,185,236,
41,132,104,127,26,185,36,228,172,179,177,120,214,214,214,75,143,152,70,50,84,100,106,240,188,106,198,96,183,21,136,56,101,66,228,49,90,8,136,76,69,150,140,191,120,207,208,185,192,14,192,53,33,106,17,229,
146,22,48,250,34,237,182,72,150,67,140,139,226,28,81,46,49,7,92,85,46,240,84,186,220,131,251,247,239,59,122,100,148,40,104,109,140,49,253,217,73,93,136,60,230,202,11,57,7,242,125,181,26,102,5,120,132,
16,109,40,44,199,194,126,17,89,37,140,2,28,48,71,204,130,53,220,201,184,160,22,125,203,16,40,198,102,229,67,77,128,244,67,82,109,29,112,135,202,132,24,23,212,101,80,210,69,52,28,203,4,24,27,218,170,178,
129,9,253,204,53,53,151,40,93,48,165,169,221,192,55,81,9,51,5,113,241,12,216,72,31,172,200,169,149,161,173,190,22,116,106,152,11,102,209,45,30,99,31,0,187,184,109,27,166,39,181,249,31,162,92,108,91,138,
185,81,203,243,112,225,17,35,243,0,217,30,181,98,143,152,182,172,110,61,224,92,35,167,113,193,93,151,184,29,240,126,200,255,213,110,204,179,216,174,108,205,1,27,44,95,173,193,48,110,137,155,208,172,27,
196,85,27,3,60,182,232,166,76,107,152,39,182,221,16,89,23,36,223,107,193,23,231,127,87,130,186,210,218,23,130,64,137,136,185,99,240,58,32,37,85,139,148,135,251,105,5,204,21,169,69,198,194,42,18,212,49,
130,186,220,200,39,17,240,174,155,45,94,145,42,152,1,4,101,106,95,84,220,41,93,26,181,44,215,147,60,48,55,209,218,13,150,239,116,118,155,116,110,29,210,20,181,9,123,219,69,53,157,49,111,88,208,29,169,
167,174,239,209,17,191,80,171,24,119,80,92,24,231,139,243,139,122,50,181,168,137,47,60,26,98,1,142,242,133,192,221,178,207,69,37,215,100,74,227,186,224,153,116,125,87,113,227,100,110,232,168,94,104,130,
191,86,81,31,98,100,222,161,24,175,35,62,60,146,174,239,39,172,162,137,247,21,185,168,93,98,12,203,168,155,58,125,186,33,44,95,223,247,97,224,101,133,32,178,174,136,91,124,249,12,18,6,11,81,58,57,31,82,
68,120,37,113,125,107,110,103,120,38,220,52,29,173,43,39,114,79,53,49,134,43,20,187,11,187,144,248,52,240,42,162,248,190,22,112,105,223,252,120,174,163,115,131,98,236,178,140,237,1,194,252,133,187,185,
137,255,254,4,59,17,76,34,157,125,55,186,176,124,138,79,14,75,165,250,6,12,119,243,136,212,145,207,82,144,143,133,199,252,173,111,174,87,122,25,46,53,146,59,68,135,230,46,215,169,38,72,154,11,109,9,162,
201,109,225,13,185,102,33,80,60,10,71,155,116,66,139,254,161,119,245,182,32,249,63,115,72,194,239,107,179,146,220,100,8,86,133,215,48,228,218,180,197,199,205,202,84,131,156,149,222,232,42,137,203,6,93,
68,89,17,37,131,119,105,150,18,75,199,205,136,207,223,182,118,199,92,3,254,213,229,148,209,64,72,177,154,123,232,96,44,45,101,88,4,132,137,11,75,244,16,113,94,43,21,66,31,87,254,62,150,27,23,49,4,71,176,
228,148,207,25,175,193,90,218,90,80,46,38,200,161,110,89,217,126,175,45,204,232,8,198,162,212,155,155,155,70,16,252,13,196,129,69,34,240,129,123,139,104,250,4,203,239,67,92,188,14,49,224,6,98,213,152,
195,113,3,224,220,99,251,242,56,135,99,4,87,19,158,77,117,229,42,48,240,176,32,81,227,120,202,96,206,4,218,22,105,28,88,168,56,218,127,43,158,91,254,190,45,176,56,106,139,99,143,177,234,188,63,34,182,
152,90,102,9,86,12,139,86,138,242,212,129,127,173,163,180,214,228,253,184,217,184,130,93,22,7,174,32,193,137,168,210,153,155,48,51,247,152,159,113,89,113,95,117,49,101,181,194,196,149,195,98,226,214,133,
213,44,221,199,16,200,41,130,45,95,155,185,184,88,55,42,129,152,207,97,193,21,156,200,238,182,173,35,46,31,162,64,168,4,82,16,9,150,9,107,138,104,16,46,7,34,66,112,252,203,255,249,29,7,207,227,249,184,
143,88,97,44,26,209,88,196,111,212,114,126,252,15,56,9,199,53,215,57,243,48,0,0,0,0,73,69,78,68,174,66,96,130,0,0};

const char* FrontEnd::minus_button_up_png = (const char*) resource_FrontEnd_minus_button_up_png;
const int FrontEnd::minus_button_up_pngSize = 4562;

// JUCER_RESOURCE: minus_button_down_png, 3750, "../../Desktop/Simpler Assets/MINUS_BUTTON_DOWN.png"
static const unsigned char resource_FrontEnd_minus_button_down_png[] = { 137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,225,0,0,0,225,8,6,0,0,0,62,179,210,122,0,0,14,109,73,68,65,84,120,218,237,157,
187,110,20,75,16,134,247,45,206,219,18,128,132,4,17,9,129,35,36,18,116,2,34,86,4,182,136,156,88,150,67,44,39,60,129,99,231,123,244,15,167,204,80,238,158,219,78,247,116,79,127,37,125,194,54,246,122,61,
211,53,117,237,234,195,1,41,70,158,158,158,254,249,245,235,215,233,238,238,238,116,115,115,115,250,241,227,199,233,120,60,158,190,126,253,122,250,244,233,211,233,226,226,226,244,241,227,199,211,135,15,
31,58,222,191,127,127,122,247,238,93,247,175,125,77,255,175,239,211,247,235,231,244,243,122,29,189,158,94,87,175,207,149,70,154,151,251,251,251,78,49,62,127,254,220,41,141,20,233,245,235,215,207,188,121,
243,166,227,237,219,183,127,161,239,155,138,255,89,123,205,254,239,145,242,234,247,127,249,242,165,123,63,122,95,220,29,100,151,10,119,117,117,213,89,38,175,104,115,21,43,21,166,164,253,247,167,247,171,
247,141,98,34,213,137,220,62,89,150,190,117,91,98,201,74,80,76,209,183,154,250,187,110,111,111,81,74,164,44,81,140,245,237,219,183,110,145,190,122,245,234,44,11,55,228,58,10,189,190,209,183,166,246,189,
254,255,135,92,220,115,44,166,94,95,241,231,247,239,223,137,49,145,109,68,9,14,197,115,182,248,231,44,234,190,162,245,45,165,22,181,94,83,10,253,243,231,207,100,232,245,245,123,244,251,250,150,110,137,
130,218,207,235,103,101,37,113,93,145,228,177,157,22,239,220,120,206,91,42,37,66,148,181,76,169,104,75,209,251,210,251,243,150,118,142,66,10,41,228,195,195,3,10,137,156,47,143,143,143,255,106,97,246,45,
214,156,197,40,107,147,218,178,229,80,76,253,29,115,148,178,111,33,245,247,179,146,144,69,238,166,44,194,20,197,235,91,58,125,92,170,149,91,83,41,237,239,157,162,148,166,144,186,158,184,171,200,168,40,
37,63,101,113,245,21,79,139,107,207,74,55,134,61,172,166,92,51,251,190,235,235,107,148,17,249,91,204,229,212,2,25,122,170,155,226,169,35,165,101,197,139,161,235,50,245,58,226,170,34,93,188,167,130,180,
146,16,83,158,224,138,139,80,180,233,88,28,57,118,109,117,253,149,240,98,69,54,36,234,207,180,238,149,161,5,98,86,111,239,49,94,142,24,114,204,58,218,131,14,101,108,64,116,147,135,44,159,45,6,21,222,81,
160,245,177,46,162,161,235,175,251,35,197,101,181,238,76,20,123,140,221,124,98,189,252,201,156,177,251,161,68,25,171,183,114,81,159,227,80,214,14,229,43,91,25,237,222,81,218,168,52,233,98,137,1,148,175,
30,101,140,197,140,118,175,88,217,149,149,27,98,79,87,50,157,229,103,84,135,30,156,106,26,103,149,23,42,234,230,31,106,64,150,107,67,194,165,158,4,78,44,155,106,247,145,21,95,104,226,101,232,9,202,226,
174,139,203,203,203,193,76,54,137,155,130,98,63,61,21,99,79,77,235,232,103,81,215,139,213,116,99,86,81,46,44,154,176,145,104,38,202,208,205,193,245,220,23,177,80,195,60,29,118,252,103,22,101,211,98,214,
79,46,140,92,25,22,238,62,187,111,116,127,99,94,143,172,38,218,177,97,242,197,92,19,22,107,27,137,155,152,85,36,105,147,80,180,253,37,246,20,212,215,107,223,60,11,243,80,172,31,11,71,244,117,10,252,43,
75,236,130,219,190,62,22,101,187,196,106,194,122,48,83,83,76,28,255,233,107,173,111,168,133,223,200,5,13,41,34,113,226,10,18,139,255,216,98,4,30,27,194,21,242,150,40,99,44,76,192,196,252,125,185,25,44,
58,136,17,202,27,216,195,28,205,154,40,26,178,52,116,33,89,104,176,52,78,212,215,25,86,60,34,26,33,31,82,64,226,63,88,43,78,212,250,98,38,234,64,7,76,76,1,229,239,179,176,96,201,22,169,80,82,79,235,76,
30,23,90,55,161,5,141,4,12,172,209,123,138,34,158,161,128,180,159,65,202,194,62,138,248,127,23,76,76,1,89,60,176,246,65,56,49,69,108,182,187,70,93,239,161,24,144,18,4,164,220,163,24,83,196,230,178,166,
177,50,4,10,8,185,74,24,161,181,215,84,33,30,5,132,45,57,30,143,209,48,104,247,10,168,157,240,177,167,16,139,3,74,136,17,119,223,89,19,74,21,147,132,129,173,143,121,107,166,215,212,142,103,166,12,1,165,
53,126,251,117,169,207,119,119,46,70,232,15,181,115,206,89,8,80,66,103,77,200,64,236,102,63,98,168,24,175,63,152,94,80,40,109,100,198,46,107,136,106,148,13,101,66,153,132,6,181,148,46,170,207,152,198,
122,246,184,225,80,203,126,196,170,19,53,177,68,12,55,26,74,70,157,92,161,240,73,249,139,170,20,80,53,24,111,5,245,185,138,164,220,104,168,97,231,69,200,128,84,211,236,173,56,144,68,12,236,97,226,119,
181,241,97,108,40,43,55,22,106,79,212,152,49,41,90,1,229,55,123,37,36,17,3,123,82,68,133,85,42,187,21,169,128,170,167,132,222,48,29,49,176,199,248,176,154,114,4,103,67,192,30,168,162,191,20,55,20,90,116,
75,53,25,162,152,253,129,161,55,168,122,11,55,15,246,220,232,93,140,91,170,22,180,144,169,230,198,65,11,110,233,230,103,93,200,28,251,55,134,27,10,45,185,165,155,79,245,14,213,81,152,19,10,173,109,123,
218,44,73,35,101,11,237,17,228,70,65,107,77,222,90,247,58,194,33,171,2,62,61,61,253,19,50,203,220,32,104,101,62,77,200,0,101,85,66,95,192,164,55,20,90,79,210,232,243,108,59,241,67,35,11,177,130,128,34,
102,44,89,248,192,84,31,95,92,92,112,83,160,249,157,22,150,152,204,94,152,199,10,2,37,139,140,214,48,100,5,153,152,6,45,163,242,132,183,134,74,220,100,179,130,20,230,1,126,6,245,34,91,70,20,43,8,240,251,
104,110,111,13,175,174,174,78,212,5,1,54,222,133,159,180,59,198,26,87,185,248,0,191,241,123,105,109,39,209,106,74,72,93,16,96,126,221,80,110,106,146,157,18,116,199,0,100,222,97,225,131,78,172,32,192,180,
158,210,85,134,6,199,118,205,115,193,1,50,21,239,253,150,126,125,204,244,52,128,56,106,225,236,235,204,217,179,104,40,206,3,108,152,160,209,38,69,159,144,161,81,27,32,227,238,10,223,39,74,44,8,48,141,
80,93,125,209,94,67,106,131,0,235,37,104,196,217,181,65,37,105,184,184,0,203,246,26,206,118,73,189,43,138,21,4,152,135,170,8,103,185,164,212,6,1,214,119,73,39,103,73,117,26,41,174,40,192,250,77,221,147,
93,82,191,111,16,43,8,176,78,150,116,114,225,158,2,61,64,26,151,116,210,217,21,161,94,81,14,119,1,88,78,168,212,55,168,132,58,6,216,199,131,28,113,6,176,94,47,233,232,246,166,208,15,112,33,1,214,107,99,
27,157,63,19,26,237,205,69,4,88,55,46,84,29,62,168,128,143,143,143,255,250,111,166,97,27,96,253,134,238,232,225,49,161,86,53,46,32,64,154,184,48,168,132,218,134,79,60,8,144,190,133,45,122,158,161,111,
56,165,62,8,144,46,46,12,30,28,227,235,25,130,139,7,144,166,143,244,197,17,219,190,72,79,191,40,64,90,37,124,113,94,133,31,101,65,105,2,32,115,114,198,55,154,146,148,1,88,23,63,147,84,134,238,254,254,
254,68,167,12,192,70,245,66,125,172,54,209,232,148,109,106,132,0,233,51,164,127,77,231,102,231,4,64,254,228,204,115,251,154,63,123,144,99,207,0,210,224,107,241,207,19,216,66,229,9,5,145,92,52,128,117,
241,231,219,63,103,72,253,76,25,202,19,0,153,203,20,106,220,102,166,12,64,122,66,165,192,78,9,53,11,145,242,4,64,122,52,165,194,27,188,135,135,135,19,187,39,0,54,172,21,42,28,124,49,226,16,37,4,200,167,
132,221,8,68,213,42,216,194,4,176,77,193,190,155,55,195,153,244,0,219,41,161,202,129,7,95,60,164,101,13,32,243,230,94,175,132,178,140,92,44,128,140,253,163,94,9,233,27,5,200,167,132,218,60,143,18,14,160,
204,177,18,85,37,226,239,155,37,213,74,132,94,228,63,248,123,167,46,26,220,209,1,5,244,243,34,97,25,186,142,140,75,9,43,97,55,107,134,196,204,180,139,5,231,65,214,253,101,157,240,249,224,80,95,162,160,
119,20,75,136,37,220,88,9,121,98,253,65,11,135,152,240,124,80,192,248,198,222,78,9,67,123,156,184,88,0,121,148,176,139,9,105,91,3,216,46,215,208,141,184,80,138,20,37,4,216,176,68,193,46,10,128,237,138,
245,221,25,246,236,39,4,216,184,109,205,79,6,70,9,1,50,239,162,208,126,38,148,16,96,195,253,132,254,132,94,138,245,0,249,118,214,119,135,133,234,80,10,148,16,96,27,37,236,14,133,97,248,47,64,30,66,35,
15,165,127,47,206,162,96,12,62,64,186,126,228,232,25,133,28,8,3,144,158,80,159,246,179,18,178,157,9,32,61,254,64,152,174,121,219,196,247,143,82,166,0,72,95,158,120,62,26,77,66,215,12,64,126,37,236,38,
173,153,232,216,94,202,20,0,121,203,19,221,244,109,19,213,42,66,90,202,133,3,72,87,158,232,14,131,233,75,200,95,229,226,1,172,67,244,128,208,152,18,178,175,16,32,237,62,194,160,18,202,242,145,156,1,200,
147,148,233,54,243,122,241,91,154,72,206,0,164,73,202,72,207,116,56,239,11,37,244,141,220,36,103,0,214,33,84,2,236,26,183,67,66,251,26,64,230,118,53,47,76,77,6,72,27,15,190,104,87,243,66,231,12,64,250,
120,240,175,78,25,47,183,183,183,196,133,0,9,227,65,233,215,221,221,93,92,9,67,113,33,59,42,0,214,115,69,85,47,60,140,9,113,33,64,58,37,236,198,222,143,137,239,113,163,94,8,176,12,133,119,125,93,210,199,
199,227,113,92,9,213,84,26,170,238,115,81,1,206,239,23,125,158,41,51,38,254,12,53,92,82,128,243,93,81,233,213,97,170,232,60,57,92,82,128,117,75,19,221,200,251,169,162,20,170,127,1,92,82,128,243,92,209,
23,251,7,199,196,155,82,92,82,128,76,174,40,46,41,192,250,89,209,89,174,104,108,228,5,13,221,0,211,8,213,218,103,187,162,184,164,0,235,185,162,178,132,135,165,226,11,247,244,146,2,12,227,195,184,232,6,
94,172,33,64,30,43,56,184,119,112,170,40,14,36,65,3,176,172,54,24,156,37,51,87,252,246,38,219,148,200,5,7,248,27,127,214,196,224,24,11,92,82,128,66,107,131,49,81,96,233,131,77,58,104,0,226,29,50,82,64,
29,47,113,88,83,176,134,0,153,19,50,99,243,103,56,209,23,224,143,21,244,186,161,57,190,135,20,226,71,121,51,42,31,96,225,8,139,165,226,207,220,198,26,66,235,248,227,35,22,247,137,18,27,2,20,28,11,78,177,
134,28,163,6,45,226,39,107,103,177,130,177,216,16,107,8,173,119,199,36,143,5,199,246,26,210,69,3,173,119,199,36,205,136,78,141,13,233,41,133,86,144,178,133,134,161,29,114,139,63,207,16,183,20,90,193,135,
99,73,186,99,166,138,127,26,88,96,202,141,130,189,162,118,77,111,124,196,97,43,185,185,185,57,113,214,61,180,94,146,88,109,167,196,57,251,13,253,83,129,36,13,180,144,13,93,109,191,96,170,36,141,98,70,
110,28,236,117,108,197,102,201,152,169,179,104,112,75,161,133,189,130,155,37,99,166,38,105,112,75,97,175,110,232,232,145,215,91,137,63,205,137,233,108,176,7,124,155,102,113,110,232,216,158,67,220,82,216,
163,27,122,246,8,195,212,18,170,161,208,77,3,123,80,64,173,237,73,39,237,110,45,58,4,49,244,230,217,105,1,53,225,13,73,241,110,104,104,48,148,15,102,41,91,64,237,229,8,53,167,28,106,18,191,227,152,222,
82,168,217,13,149,98,30,106,148,80,106,151,68,13,212,212,156,93,108,57,98,78,124,24,250,163,4,55,28,106,168,7,86,21,7,198,228,250,250,154,68,13,84,145,136,9,149,215,54,111,206,94,179,126,24,106,126,149,
159,205,2,128,210,38,166,153,5,44,190,30,120,238,233,78,150,49,165,163,6,74,235,136,177,81,158,135,61,74,204,231,190,188,188,100,65,64,118,98,30,90,21,5,249,53,183,61,81,186,128,173,230,196,132,214,226,
89,71,91,215,158,49,69,17,33,23,242,188,98,198,224,208,138,40,227,20,82,68,106,136,176,69,49,62,251,204,208,82,68,39,0,163,136,80,130,5,212,154,147,135,118,104,81,66,53,68,20,17,114,198,128,187,170,5,
46,21,141,8,136,93,28,89,75,22,16,172,145,5,141,173,177,187,187,187,182,21,112,76,17,245,53,118,94,192,185,117,192,88,15,51,10,56,67,17,25,40,12,107,117,194,160,128,19,98,196,80,178,70,79,50,122,77,97,
14,218,249,16,83,64,205,67,66,219,6,68,79,168,144,34,218,5,101,129,193,148,18,68,72,1,245,245,102,179,160,75,10,250,33,215,148,204,41,44,217,15,40,133,108,162,19,38,133,216,197,35,97,3,83,70,82,196,218,
208,118,223,11,154,90,20,11,134,178,91,250,154,206,1,96,1,66,44,254,147,82,86,59,150,162,52,137,213,121,116,225,25,167,72,252,23,11,91,118,183,31,176,212,204,169,93,112,246,37,182,87,255,139,61,152,139,
56,174,108,207,9,27,89,190,216,128,97,206,190,104,103,22,76,104,13,232,107,85,15,101,218,67,156,104,86,145,77,194,109,37,95,136,255,54,146,171,171,171,232,13,145,130,42,35,198,194,221,15,177,76,185,185,
159,116,192,108,40,177,204,152,89,69,90,222,234,70,25,240,161,135,173,188,34,180,160,0,81,82,38,118,163,236,73,201,130,174,111,235,145,30,162,177,7,172,238,105,113,135,116,182,46,234,7,140,5,236,184,168,
245,185,158,177,152,223,238,35,43,190,82,171,104,79,80,154,193,203,45,186,199,148,207,60,26,229,2,88,229,149,136,158,150,99,46,170,106,77,44,254,237,25,186,87,246,224,84,108,200,170,174,180,192,31,235,
168,55,101,84,220,129,50,110,183,223,111,232,254,152,85,164,240,190,35,23,117,72,25,177,140,249,45,223,216,253,32,241,178,67,145,146,13,101,220,236,230,147,192,73,151,112,25,114,59,205,51,209,67,147,213,
186,115,177,218,83,76,25,205,21,226,116,225,245,134,44,197,18,46,253,135,159,190,151,213,217,160,50,14,89,198,254,2,33,163,58,29,77,201,83,166,115,236,65,103,150,15,229,67,158,183,74,141,45,24,61,205,
45,83,135,178,205,143,245,188,151,193,86,35,228,133,104,81,140,185,78,40,100,88,241,166,92,51,83,80,101,173,89,109,200,160,200,157,154,250,84,239,43,164,62,223,123,12,105,94,195,148,107,211,87,62,61,172,
40,53,32,103,149,55,134,90,226,66,139,206,178,172,181,43,165,254,254,190,181,155,115,13,244,47,46,39,178,154,104,171,140,237,230,158,186,24,189,165,52,139,80,170,98,154,194,41,89,178,228,239,180,159,145,
181,100,180,32,146,77,33,167,186,101,126,252,94,95,49,109,34,152,54,165,30,143,199,228,187,19,244,222,237,248,114,123,15,115,20,46,166,120,12,213,69,54,17,45,60,89,16,235,113,92,178,152,67,10,218,87,82,
67,22,202,232,255,46,251,94,255,255,125,5,51,98,155,99,231,88,117,189,190,148,152,102,106,164,72,81,230,79,22,205,43,229,210,133,191,21,222,90,171,238,167,135,13,59,216,145,234,68,25,65,37,39,172,75,167,
52,197,12,185,199,250,88,46,171,122,55,113,49,145,221,42,166,92,57,89,76,185,117,102,53,189,251,104,10,178,68,97,253,207,134,92,92,89,55,117,2,41,158,147,5,71,225,16,228,240,123,172,163,92,62,41,133,20,
85,137,20,41,137,44,147,172,169,148,70,138,43,164,68,82,56,253,171,207,245,127,66,223,167,239,151,251,40,43,44,139,118,115,115,211,213,233,200,90,150,39,255,1,151,224,115,222,118,153,136,128,0,0,0,0,73,
69,78,68,174,66,96,130,0,0};

const char* FrontEnd::minus_button_down_png = (const char*) resource_FrontEnd_minus_button_down_png;
const int FrontEnd::minus_button_down_pngSize = 3750;


//[EndFile] You can add extra defines here...
//[/EndFile]
